"Arcisate",ARCISATE,,4550.967N,00853.100E,350.0m,2,0,,,,"FUORICAM",, DEPRECATED BY http://www.ava-valbrembo.it/campi-atterrabili/
"Cortina",CORTINA,,4632.000N,01208.000E,1150.0m,2,0,,,,"FUORICAM",, SECONDO ME QUESTO E' SBAGLIATO, CHE IO SAPPIA A CORTINA CI SONO DUE ATTERRAGGI: L'EX AEROPORTO E IL CAMPEGGIO
"Brezzo",BREZZO,,4557.983N,00842.000E,320.0m,2,0,,,,"FUORICAM",, DEPRECATED BY http://www.ava-valbrembo.it/campi-atterrabili
"Paré",PARÉ,,4548.383N,00859.400E,350.0m,2,0,,,,"FUORICAM",, 	 DEPRECATED BY http://www.ava-valbrembo.it/campi-atterrabili
"Tolmin",TOLMIN,,4611.317N,01342.300E,170.0m,2,0,,,,"FUORICAM",, QUESTO E' QUELLO VECCHIO INUTILIZZABILE, ADESSO A TOLMINO CE N'E' UNO DIVERSO, CON SCHEDA A http://www.cvne.it/index.php?option=com_content&view=article&id=84&catid=14


