name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc,userdata,pics
"AIGENLOXA_AE",AIGENOXA,,4732.000N,01408.000E,700.0m,2,0,,,"118.00 sourceSAP",,,
"ALZATE LILB",ALZATILB,,4546.167N,00909.667E,390.0m,2,0,,,,"3-21/123 sourceSAP",,
"AMBRI LSPM",AMBRISPM,,4630.500N,00841.000E,1004.0m,2,0,,,"118.52 sourceSAP",,,
"AOSTA LIMW",AOSTAIMW,,4544.317N,00721.750E,545.0m,2,0,,,,"7-09/119 sourceSAP",,
"ASIAGO LIDA",ASIAGIDA,,4553.167N,01130.933E,1020.0m,2,0,,,,"8-26/122 sourceSAP",,
"BADRAGAZLSZE",BADRASZE,,4700.900N,00928.900E,493.0m,2,0,,,"123.5 sourceSAP",,,
"BIELLA_AE",BIELLILE,,4529.967N,00806.133E,282.0m,2,0,,,,"6-34/123 sourceSAP",,
"BOSCO_AE",BOSCOAE,,4528.300N,01055.067E,91.0m,2,0,,,,"Aeroporto",,
"CALCINATE_AE",CALCIATE,,4548.550N,00846.100E,242.0m,2,0,,,"128.45","0-28/128  sourceSAP",,
"GRENOBLE_AE",GRENOFLG,,4521.800N,00520.000E,220.0m,2,0,,,"121.00","sourceSAP",,
"KAPFENB_AE",KAPFEOGK,,4727.500N,01519.783E,515.0m,2,0,,,,"ANGAR/11  sourceSAP",,
"KLAGENF_AE",KLAGEOWK,,4638.567N,01420.267E,448.0m,2,0,,,,"0-28/118 sourceSAP",,
"LANZENT_AE",LANZE,,4733.400N,01519.400E,770.0m,2,0,,,"122.5",,,
"LOCARNO_AE",LOCARSZL,,4609.417N,00852.167E,197.0m,2,0,,,"134.82 ",,,
"LUGANO_AE",LUGANSZA,,4600.200N,00854.600E,277.0m,2,0,,,"120.25 ",,,
"MASERA AVIO",MASERVIO,,4608.383N,00818.717E,297.0m,2,0,,,"130.00"," sourceSAP",,
"NIEDEROBLOGO_AE",NIEDEOGO,,4728.700N,01400.500E,653.0m,2,0,,,"122.7",,,
"SAMEDAN_AE",SAMEDSZS,,4631.500N,00953.633E,1709.0m,2,0,,,"119.42 ",,,
"STJOHAN_AE",ST.JOOIJ,,4731.200N,01226.900E,670.0m,2,0,,,"120.35 ",,,
"TIMMERS_AE",TIMMEOGT,,4722.800N,01458.100E,628.0m,2,0,,,"122.3  ",,,
"TORINO_AE",TORINIMA,,4504.900N,00736.467E,288.0m,2,0,,,,"0-28/119",,
"TRAUSDORF_AE",TRAUSORF,,4748.850N,01633.600E,150.0m,2,0,,,,"Aeroporto",,
"TRIEBENLOGI",TRIEBOGI,,4729.600N,01429.800E,690.0m,2,0,,,"122.5  ",,,
"VALBREMB_AE",VALBRILV,,4543.200N,00935.633E,230.0m,2,0,,,,"2-20/122",,
"VENEGONO_AE",VENEGILN,,4544.433N,00853.217E,320.0m,2,0,,,,"6-18/128",,
"VERGIATE_AE",VERGIILG,,4542.750N,00841.967E,263.0m,2,0,,,"119.65 ",,,
"WIENERN_AE",WIENEOXN,,4750.400N,01613.200E,280.0m,2,0,,,"123.25 ",,,
"WOLFSBER_AE",WOLFSOKW,,4649.100N,01449.583E,450.0m,2,0,,,"122.50 ",,,
"ZELLAMSE_AE",ZELLAOWZ,,4717.600N,01247.200E,754.0m,2,0,,,"119.7  ",,,
"Innsbruck_AE",LOWI,AT,4715.617N,01120.633E,581.3m,5,81,2000.0m,,"119.275","119.275 INNSBRUCK RADAR120.100 INNSBRUCK TOWER126.025 INNSBRUCK INFORMATION123.400 INNSBRUCK SEGELFLUG Transition Altitude for IFR as instructed by ATC",,
"Kufstein_AE",LOIK,AT,4733.850N,01207.650E,484.0m,2,55,800.0m,,"122.380","122.380 KUFSTEIN INFO(GE/EN)",,
"Šoštanj_AE",LJSO,SI,4623.870N,01502.707E,378.0m,5,150,700.0m,,"128.300","128.300 SOSTANJ AERODROME (EN/SLO) Intense glidin RC model flying. Without radio contact always land on RW 33! sourceSEEYOU",,
"Celje_AE",LJCL,SI,4614.615N,01513.527E,244.0m,2,112,900.0m,,"128.800","128.800 CELJE AERODROME (EN/SLO) Itense Gliding activity RC model flying Flight school operations Winching",,
"Slo_Gradec_AE",LJSG,SI,4628.285N,01507.055E,501.0m,5,142,1200.0m,,"123.500","123.500 SLOVENJ GRADEC AERODROME (EN/SLO) Winching Intense Gliding Aerobatics RC model flying.",,
"Ferlach_AE",LOKG,AT,4632.000N,01419.899E,456.6m,2,140,618.0m,,"123.605","123.605 GLAINACH INFO",,
"Grobnik_AE",LDRG,HR,4522.773N,01430.210E,308.5m,5,75,1598.0m,,,,,
"Rijeka_AE",LDRI,HR,4513.013N,01434.216E,84.7m,5,144,2500.0m,,"119.000","119.000 TOWER125.425 TOWER121.500 TOWER",,
"Podpec_UL",Podpec,SI,4558.467N,01425.083E,288.0m,2,80,500.0m,,"123.500","Private airfield. Not meant for public use. Use north air traffic pattern only.",,
"Ljubljana_AE",LJLJ,SI,4613.467N,01427.367E,388.0m,5,126,3300.0m,,"118.000","118.000 LJUBLJANA TOWER118.750 LJUBLJANA TOWER135.275 LJUBLJANA APPROACH132.475 LJUBLJANA APPROACH128.175 LJUBLJANA ATIS112.700 LJUBLJANA ATIS121.925 LJUBLJANA GROUND131.400 LJUBLJANA HANDLING131.800 GENERAL AVIATION131.400 LJUBLJANA DE-ICING COORDINATOR131.700 LJUBLJANA DE-ICING",,
"Zagorje_AE",Ruardi,SI,4608.550N,01459.917E,332.0m,2,40,450.0m,,"123.500",,,
"Slovenske Konjice_AE",LJSK,SI,4618.717N,01529.483E,274.0m,2,159,600.0m,,"123.550","123.550 SLOVENSKE KONJICE AERODROME",,
"Maribor_AE",LJMB,SI,4628.792N,01541.168E,267.0m,5,146,2500.0m,,"119.200","119.200 MARIBOR TOWER134.300 MARIBOR TOWER MON - SUN: 0630 - 1800 (0600 - 1800)",,
"Chatelair_UL",CHATE,IT,4544.400N,00728.833E,503.0m,2,100,450.0m,,,"sourceSEEYOU,,",,
"Montalto_UL",MONTA,IT,4529.400N,00750.500E,246.0m,2,140,620.0m,,,,,
"Flying Tigers_UL",FLYIN,IT,4526.460N,00756.220E,235.0m,5,46,1750.0m,,,,,
"Castellamonte_UL",CASTE,IT,4521.480N,00743.200E,311.0m,2,130,365.0m,,,,,
"Busano_UL",BUSAN,IT,4518.650N,00739.917E,295.0m,2,180,400.0m,,,,,
"Prealpi-Musinè_UL",PREAL,IT,4507.512N,00731.320E,331.0m,2,30,600.0m,,,,,
"Rivoli_UL",RIVOL,IT,4502.820N,00732.160E,305.0m,2,300,300.0m,,,,,
"Cumiana_UL",CUMIA,IT,4457.350N,00726.350E,274.0m,2,140,450.0m,,,,,
"Andrea Bozzo_UL",ANDRE,IT,4451.840N,00724.420E,260.0m,5,43,2965.0m,,,,,
"Merlo Romano_UL",MERLO,IT,4450.040N,00721.840E,315.0m,2,100,450.0m,,,,,
"Brezzo_??",BREZZO,,4557.983N,00842.000E,320.0m,2,0,,,,"DEPRECATED BY http://www.ava-valbrembo.it/campi-atterrabili, ma al SAP viene usato sourceSAP",,
"Mauterndorf_AE",LOSM,AT,4707.929N,01341.771E,1110.1m,2,70,820.0m,,"122.855","122.855 MAUTERNDORF INFO(GE)",," "
"Mayerhofen_UL",LOKM,AT,4658.500N,01422.274E,646.0m,2,81,400.0m,,"122.855","122.855 MAYERHOFEN INFO (GE) Vienna Info: 124.40",,
"Friesach_AE",LOKH,AT,4655.656N,01425.881E,615.0m,2,172,460.0m,,"122.080","122.080 FRIESACH INFO(GE) Vienna Info Fqr.: 12440 MHz",,
"Mairist / St. Donat_UL",LOKR,AT,4644.597N,01424.811E,536.1m,2,64,400.0m,,,,,
"Zeltweg_AE",LOXZ,AT,4712.250N,01444.805E,690.1m,5,80,2750.0m,,"135.375","135.375 ZELTWEG SEGELFLUG129.475 ZELTWEG RADAR132.650 ZELTWEG RADAR123.500 ZELTWEG SEGELFLUG121.600 ZELTWEG GROUND(GE/EN) Civil use of military air bases see AD 1.",,
"Mariazell_AE",LOGM,AT,4747.367N,01518.017E,859.8m,5,147,500.0m,,"122.105","122.105 MARIAZELL INFO(GE) Occupied on Saturdays Sundays and public holidays. Otherwise recommended a previous request.",,
"BRUNET LE GRAND LOGISSON_?",BRUNE,FR,4353.323N,00603.198E,663.0m,5,115,2100.0m,,,,,
"Lodrino_AE",LSML,CH,4618.000N,00900.000E,259.0m,5,161,641.0m,,"119.625","119.625 LODRINO AD (EN/IT)",,
"Münster_AE",LSPU,CH,4628.817N,00815.800E,1350.0m,5,48,661.0m,,"122.075","122.075 MÜNSTER AD (EN/GE)",,
"Raron_AE",LSTA,CH,4618.233N,00749.017E,637.0m,5,91,719.0m,,"126.975","126.975 RARON AD (EN/GE) Airport derzeit im Umbau",,
"Bex_AE",LSGB,CH,4615.474N,00659.196E,399.9m,2,147,720.0m,,"122.150","122.150 AERODROME DE BEX(FR) AD circuits for RWY 15 prohibited to visiting ACFT.  Touch-and-go prohibited.  CAUTION! BTN RWY and GRASS PRKG area public road that is no TWY.  No hangar.  NOV till end of MAR: CLSD to visiting ACFT.  At least a half AD circuit must be flown prior to LDG.",,"	"
"Tolmin_6",TOLMIN,,4611.066N,01343.197E,170.0m,2,0,,,,"Nuovo fuoricampo, sourceCVNE, atterare solo da N in centro, in alternativa il campo para ma da S",,
"Malpasso_7?",MALPASSO,,4507.667N,00712.267E,416.0m,2,0,,,,"FUORICAM sourceSAP",,
"Malnate_4",Malna,IT,4547.035N,00852.811E,350.0m,3,80,,,,"Emergenza source:Flavio verificare",,
"FORNAZZA_?",FORNA,IT,4621.876N,00825.874E,1255.0m,3,18,,,,"source:Flavio",,
"EX_PAF???_4",EXPAF,IT,4529.603N,01053.202E,103.0m,3,,,,,"Emergenza vicino a verona. Da controllare le coordinate. Video di Andrea Salvadori",,
"SVITTORE_8",LSXV,CH,4614.183N,00906.050E,261.0m,2,80,800.0m,,"122.07","En/De | Mil | NO GLD",,
"MONTORIO_6",MTOR_6,IT,4527.083N,01102.567E,59.0m,3,160,400.0m,,,"attenzione cavi telefono e bassa tensione testata 160 sourceAVS Check 2021 Salvadori",,
"VIDOR_N_7",VIDN_7,IT,4551.417N,01202.513E,145.0m,3,280,300.0m,,,"SAN21 NUOVO VIDOR: source webinars",,
"CAPRINO_7",CAPRI_7,IT,4535.391N,01045.615E,211.0m,3,10,,,,"SAN21 nuovo atterraggio di Caprino. atterrare verso N Non atterrare a Costermano",,
"BUSTI_7",BUSTI7,,4527.133N,01101.033E,50.0m,3,360,400.0m,,,"cavo telefono testata 360 sourceAVS e webinar",,
"ABFALTERSBACH KatB_?",ABFALT_B,AT,4645.500N,01232.320E,1000.0m,3,70,200.0m,,,"Kat B 07/25 Viele, viele Zaunstempel in der Wiese. Das naheliegende Sillian ist besser! sourceAVS",,
"ACHENKIRCH NORD KatB_?",ACHENN_B,AT,4732.240N,01142.400E,900.0m,3,170,200.0m,,,"Kat B 17/35 Achtung, versteckte Pfloecke in der Wiese! sourceAVS",,
"ACHENKIRCH SUED KatA_?",ACHENK_A,AT,4730.820N,01142.120E,936.0m,3,270,250.0m,,,"Kat A -/27  Landung nur Richtung Westen, leicht ansteigend. Landung auch rechts der Strasse moeglich! sourceAVS",,
"ADMONT KatA_?",ADMONT_A,AT,4734.995N,01427.156E,630.0m,3,90,450.0m,,,"Kat A 09/-  Zwischen Stromleitung und Strasse, Bauer unfreundlich, keine Zufahrt, Flugzeug muss ueber Zaun zur Strasse gehoben werden. sourceAVS",,
"AICH ASSACH KatA_?",AICHAS_A,AT,4725.480N,01351.460E,730.0m,3,360,400.0m,,,"Kat A -/36  Leicht ansteigend. sourceAVS",,
"AICH KatA_?",AICH_A,AT,4725.100N,01348.600E,700.0m,3,60,,,,"Kat A 06/24  sourceAVS",,
"AICHLMUEHL KatB_?",AICHLM_B,AT,4750.720N,01550.230E,550.0m,3,50,200.0m,,,"Kat B 05/23  sourceAVS",,
"ALMSEE KatB_?",ALMSEE_B,AT,4744.600N,01357.000E,600.0m,3,230,230.0m,,,"Kat B -/23  Talwind als Rueckenwind! sourceAVS",,
"ALTENMARKT KatB_?",ALTENM_B,AT,4722.972N,01324.496E,850.0m,3,60,,,,"Kat B 06/-  Wird sporadisch als Weide genutzt! sourceAVS",,
"ALTMUENSTER KatA_?",ALTMUE_A,AT,4752.880N,01346.180E,450.0m,3,260,330.0m,,,"Kat A -/26   sourceAVS",,
"ANDELSBUCH KatA_?",ANDELS_A,AT,4725.180N,00953.410E,610.0m,3,10,,,,"Kat A 01/19  sourceAVS",,
"ASCHAU KatB_?",ASCHAU_B,AT,4716.286N,01153.768E,560.0m,3,250,300.0m,,,"Kat B -/25   sourceAVS",,
"ASCHBACH KatB_?",ASCHBA_B,AT,4740.065N,01520.290E,850.0m,3,150,320.0m,,,"Kat B 15/-   sourceAVS",,
"AUSSERBRAZ KatB_?",AUSSER_B,AT,4708.670N,00954.530E,690.0m,3,90,,,,"Kat B 09/27  sourceAVS",,
"BACH KatA_?",BACH_A,AT,4716.050N,01023.900E,1060.0m,3,40,300.0m,,,"Kat A 04/-  Ueber die gesamte Laenge eben, Achtung ev. Weidezaeune! sourceAVS",,
"BAD GOISERN KatB_?",BADGOI_B,AT,4737.600N,01336.640E,570.0m,3,220,400.0m,,,"Kat B -/22  Weinbach bevorzugen, da nahe gelegen! sourceAVS",,
"BAD ISCHL KatA_?",BADISC_A,AT,4743.464N,01334.411E,500.0m,3,340,400.0m,,,"Kat A -/34  sanfter Anstieg am Ende sourceAVS",,
"BAD-HOFGASTEIN-NORD KatA_?",BHOF-N_A,AT,4710.822N,01306.080E,835.0m,3,180,300.0m,,,"Kat A 18/36 In Feldmitte eine ca. 30 m im Durchmesser , ca .1 m hohe Stelle mit Wall, gekennzeichnet mit Holzstempen! sourceAVS",,
"BAD-HOFGASTEIN-SUED KatB_?",BHOF-S_B,AT,4708.854N,01307.069E,848.0m,3,170,250.0m,,,"Kat B 17/35 Zaeune beachten! sourceAVS",,
"BLUDENZ KatB_?",BLUDEN_B,AT,4708.659N,00950.331E,580.0m,3,90,,,,"Kat B 09/27  sourceAVS",,
"BOCKING KatB_?",BOCKIN_B,AT,4730.960N,01213.650E,690.0m,3,170,300.0m,,,"Kat B 17/-  Landerichtung nur SO, Feld steigt an sourceAVS",,
"BODENBAUER HOCHSCHWAB KatB_?",BODENB_B,AT,4734.781N,01506.913E,870.0m,3,300,300.0m,,,"Kat B -/30   sourceAVS",,
"BRAMBERG KatA_?",BRAMBE_A,AT,4715.615N,01219.435E,830.0m,3,250,500.0m,,,"Kat A 25/07 Von Ost freier Anflug, jedoch leicht abschuessig.Wiese haengt ein klein wenig nach Sueden. sourceAVS",,
"Brebbia_ul?",BREBBIA,,4549.200N,00839.200E,260.0m,2,0,,,,"Ex pista ULM, dovrebbe essere ancora utilizzabile sourceSAP",,
"BREDERIS KatA_?",BREDIS_A,AT,4717.430N,00937.050E,440.0m,3,20,300.0m,,,"Kat A 02/20 Felder wurden zum Golfplatz umgebaut! sourceAVS",,
"BRIXEN IM THALE KatA_?",BRIXET_A,AT,4727.072N,01215.969E,830.0m,3,100,400.0m,,,"Kat A 10/-  Wiese 1, geht nicht mehr: Bau einer Umgehungsstrasse!!!!Wiese 2, rosa Querweg nur mit Rumps zu ueberrollen ! sourceAVS",,
"BRUNNSEE KatB_?",BRUNNS_B,AT,4739.000N,01502.500E,640.0m,3,200,300.0m,,,"Kat B -/20   sourceAVS",,
"DOLLINGER KatB_?",DOLLIN_B,AT,4716.369N,01047.742E,788.0m,3,50,418.0m,,,"Kat B 05/23 Moorwiesen! sourceAVS",,
"DORFGASTEIN KatB_?",DORFGA_B,AT,4713.453N,01306.519E,830.0m,3,180,450.0m,,,"Kat B 18/36 Drachenflieger- und Modellfliegerplatz mit Windsack. sourceAVS",,
"EHRWALD KatB_?",EHRWAL_B,AT,4723.936N,01054.830E,970.0m,3,110,250.0m,,,"Kat B 11/-  am Ostrand fuehrt eine Leitung ueber das Feld > Landerichtung nur gegen Osten. sourceAVS",,
"Eisenkappel_?",KA,AT,4630.500N,01434.833E,510.0m,3,150,200.0m,,,"DATI PROVENIENTI NON DAL CVAO. The data are not from CVAO. sourceAVS",,"N093E014_0038.jpg"
"ELLMAU KatB_?",ELLMAU_B,AT,4731.044N,01217.686E,780.0m,3,120,360.0m,,,"Kat B 12/-  Wiese 1 steigt leicht nach Osten an! Stangen im Fruehjahr ! sourceAVS",,
"ERPFENDORF KatA_?",ERPFEN_A,AT,4734.661N,01228.962E,644.0m,3,80,500.0m,,,"Kat A 08/-  Von West nach Ost leicht ansteigend. sourceAVS",,
"FRIESACHLOKH_AE",FRIESOKH,,4830.900N,01424.500E,610.0m,2,0,,,"122.07 sourceSAP",,,
"FRIESACH-GRAZ KatA_?",FRIEGA_A,AT,4709.911N,01519.533E,390.0m,3,10,300.0m,,,"Kat A 01/19  sourceAVS",,
"FUEGEN KatA_?",FUEGEN_A,AT,4720.654N,01151.515E,540.0m,3,270,600.0m,,,"Kat A -/27  Hohe Baeume und 2 Hochspannungen im Osten beachten ! Im Westen: Bahn-Boeschung  und unterrollbare Hochspannung! sourceAVS",,
"GAGERING KatA_?",GAGERI_A,AT,4721.650N,01151.391E,530.0m,3,170,730.0m,,,"Kat A 17/35 Auf viele Stromleitungen achten, noerdliche Wiese beste Variante. sourceAVS",,
"GALTUER KatB_?",GALTUE_B,AT,4658.400N,01012.030E,1580.0m,3,50,300.0m,,,"Kat B 05/23 sehr enges Tal, in der Mitte sumpfiger Fleck mit ca. 10m Durchmesser! sourceAVS",,
"GIPPEL-WEISSENBACH KatA_?",GIPPEL_A,AT,4749.990N,01536.420E,690.0m,3,110,500.0m,,,"Kat A 11/29  sourceAVS",,
"Gloggnitz_?",AT,AT,4740.617N,01557.667E,430.0m,3,110,400.0m,,,"DATI PROVENIENTI NON DAL CVAO; DAL SITO www.landewiesen.org . The data are not from CVAO. sourceAVS",,"N095E015_0111.jpg;N095E015_img901.jpg;N095E015_img904.jpg"
"GOESTLING KatA_?",GOESTL_A,AT,4746.785N,01454.512E,580.0m,3,230,350.0m,,,"Kat A -/23   sourceAVS",,
"GOETZIS KatA_?",GOETZI_A,AT,4719.134N,00937.601E,425.0m,3,20,300.0m,,,"Kat A 02/20  sourceAVS",,
"GOGGAU KatA_?",GOGGAU_A,AT,4647.942N,01409.005E,785.0m,3,40,600.0m,,,"Kat A 04/22  sourceAVS",,
"GORTIPOHL KatB_?",GORTIP_B,AT,4700.266N,01000.283E,900.0m,3,150,300.0m,,,"Kat B 15/33 Enges Tal! sourceAVS",,
"GOSAU KatA_?",GOSAU_A,AT,4733.900N,01331.220E,750.0m,3,20,400.0m,,,"Kat A 02/20  sourceAVS",,
"GRABENWEG KatA_?",GRABEN_A,AT,4757.030N,01601.930E,413.0m,3,60,800.0m,,,"Kat A 06/24  sourceAVS",,
"GRAFENBACH KatA_?",GRAFEN_A,AT,4741.055N,01600.144E,410.0m,3,160,800.0m,,,"Kat A 16/-   sourceAVS",,
"GRAMLER KatB_?",GRAMLE_B,AT,4729.966N,01247.331E,676.0m,3,120,450.0m,,,"Kat B 12/30 Sehr enges Tal, keine Platzrunde moeglich. sourceAVS",,
"GRIESSENPASS KatB_?",GRISSE_B,AT,4727.311N,01239.282E,960.0m,3,280,500.0m,,,"Kat B -/28   sourceAVS",,
"GSCHOEDER KatB_?",GSCHOE_B,AT,4738.834N,01506.689E,650.0m,3,160,,,,"Kat B 16/_sourceAVS",,
"GUSSWERK KatB_?",GUSSWE_B,AT,4743.396N,01516.260E,720.0m,3,30,,,,"Kat B 03/-   sourceAVS",,
"HABACH KatA_?",HABACH_A,AT,4746.866N,01409.700E,500.0m,3,330,550.0m,,,"Kat A -/33  Landerichtung 33 wegen lokaler Windsystem bevorzugen! sourceAVS",,
"HAIMING-PIRCHET KatA_?",HAIMIN_A,AT,4715.555N,01054.532E,670.0m,3,800,400.0m,,,"Kat A 80/26 Suedliches Landefeld Querwege ueberrollbar.Maisanbau! sourceAVS",,
"HAINFELD KatB_?",HAINFE_B,AT,4801.964N,01546.791E,426.0m,3,100,260.0m,,,"Kat B 10/28 Kurz und schlechter Anflug ueber Wald. sourceAVS",,
"HALLTAL KatB_?",HALLTA_B,AT,4745.920N,01520.960E,780.0m,3,300,350.0m,,,"Kat B -/30   sourceAVS",,
"HAUS-ENNSTAL KatA_?",HAUS_A,AT,4725.060N,01346.802E,700.0m,3,70,,,,"Kat A 07/25  sourceAVS",,
"HEITERWANG KatA_?",HEITER_A,AT,4726.579N,01045.237E,1000.0m,3,140,500.0m,,,"Kat A 14/32 Achtung Pfloecke, mehrere Moeglichkeiten. sourceAVS",,
"HINTERGLEMM KatB_?",HINTER_B,AT,4723.020N,01236.545E,1028.0m,3,250,300.0m,,,"Kat B -/25  Anflug ueber 10 m hohe Baeume! sourceAVS",,
"HINTERSTODER KatB_?",HINSTO_B,AT,4740.444N,01407.141E,640.0m,3,40,380.0m,,,"Kat B 04/22  sourceAVS",,
"HOCHFILZEN KatA_?",HOCHFI_A,AT,4728.283N,01237.183E,960.0m,3,140,400.0m,,,"Kat A 14/-  Landerichtung SO, Feld steigt leicht an. sourceAVS",,"N094E012_img203.jpg"
"HOCHKAR-LASSING KatB_?",HOCHKA_B,AT,4745.320N,01454.230E,680.0m,3,200,300.0m,,,"Kat B -/20  Drachenfliegerlandeplatz sourceAVS",,
"HOFKIRCHEN-ST-STEFAN KatB_?",HOFKIR_B,AT,4714.800N,01553.400E,345.0m,3,150,300.0m,,,"Kat B 15/33  sourceAVS",,
"HOHE-WAND KatA_?",HOHE-W_A,AT,4749.382N,01604.797E,380.0m,3,320,320.0m,,,"Kat A -/32   sourceAVS",,
"HUBEN OETZTAL KatA_?",HUBEN_A,AT,4702.779N,01057.918E,1189.0m,3,150,700.0m,,,"Kat A 15/33 Unregelmaessig ca. 50 cm hohe Begrenzungs-Stempen, vor allem am Witschaftsweg! Weg ueberrollbar. sourceAVS",,
"IMST KatB_?",IMST_B,AT,4713.167N,01044.750E,714.0m,3,100,400.0m,,,"Kat B 10_Landung nur Richtung Osten wegen Hochspannungsleitung sourceAVS",,"N094E010_0006.jpg;N094E010_img221.jpg"
"IMST-ARZL KatA_?",IMSTAZ_A,AT,4712.583N,01045.914E,880.0m,3,70,300.0m,,,"Kat A 07/25 Nur nutzen wenn Imst nicht nutzbar, da Imst 170m tiefer liegt sourceAVS",,
"INNERFAHRAFELD KatB_?",INNERF_B,AT,4756.270N,01535.912E,450.0m,3,160,350.0m,,,"Kat B 16/-   sourceAVS",,
"INNERHALBACH KatB_?",INNERH_B,AT,4755.940N,01541.390E,550.0m,3,50,300.0m,,,"Kat B 05/23 Baum im Endanflug 05! sourceAVS",,
"INNERZWAIN KatA_?",INNERZ_A,AT,4733.476N,01509.248E,775.0m,3,320,350.0m,,,"Kat A -/32   sourceAVS",,
"INNSBRUCLOWI_za?",INNSBOWI,,4715.600N,01126.600E,580.0m,2,0,,,"122.1  ZA sourceSAP",,,
"JAUSERN KatB_?",JAUSER_B,AT,4722.400N,01241.400E,910.0m,3,300,380.0m,,,"Kat B -/30  Anflug ueber 10 m hohe Klaeranlage oder Bauernhof.Die vorhandenen Wege sind eingeebnet und ueberrollbar!Im Suedteil eine Stufe! sourceAVS",,
"JOHNSBACH KatB_?",JOHNSB_B,AT,4731.731N,01437.095E,865.0m,3,100,300.0m,,,"Kat B 10/-   sourceAVS",,
"KALWANG KatB_?",KALWAN_B,AT,4725.500N,01444.000E,760.0m,3,0,,,,"Kat B  sourceAVS",,
"KAPELLEN-MUERZ KatA_?",KAPELL_A,AT,4738.992N,01537.289E,700.0m,3,110,500.0m,,,"Kat A 11/29 Anflug 29 ueber Tennisplaetze bzw. 11 ev. mit kleinem Schlenkerer ueber niedrigen Waldruecken und Baeume am Muerzufer sourceAVS",,
"KATZLING KatA_?",KATZLI_A,AT,4714.560N,01431.830E,860.0m,3,140,,,,"Kat A 14/32  sourceAVS",,
"KERNHOF KatB_?",KERNHO_B,AT,4748.672N,01532.899E,700.0m,3,140,,,,"Kat B 14/-   sourceAVS",,
"KIENZEN KatA_?",KIENZE_A,AT,4730.100N,01030.500E,1090.0m,3,270,300.0m,,,"Kat A -/27   sourceAVS",,
"KITZBUEHEL KatA_?",KITZBU_A,AT,4725.832N,01224.361E,765.0m,3,160,400.0m,,,"Kat A 16/34  sourceAVS",,
"KLAUS KatB_?",KLAUS_B,AT,4718.210N,00938.110E,450.0m,3,100,150.0m,,,"Kat B 10/28  sourceAVS",,
"KOESSEN KatA_?",KOESSE_A,AT,4739.486N,01222.867E,615.0m,3,240,500.0m,,,"Kat A -/24   sourceAVS",,
"KRAMSACH KatA_?",KRAMSA_A,AT,4726.913N,01153.933E,515.0m,3,60,500.0m,,,"Kat A 06/24  sourceAVS",,
"KRIEGLACH KatA_?",KRIEGL_A,AT,4732.500N,01532.650E,620.0m,3,160,,,,"Kat A 16/-  Holzpfloecke! sourceAVS",,
"KRIMML KatB_?",KRIMML_B,AT,4713.433N,01210.650E,1040.0m,3,240,400.0m,,,"Kat B -/24  Stark ansteigend! sourceAVS",,"N094E012_0009.jpg;N094E012_img243.jpg;N094E012_img246.jpg"
"KRIPPAU KatA_?",KRIPPA_A,AT,4741.300N,01442.250E,505.0m,3,120,280.0m,,,"Kat A 12/-  Wiese beginnt von Westen mit Stacheldrahtzaun, von Osten mit 5m Hecke! sourceAVS",,
"KUEB KatB_?",KUEB_B,AT,4741.000N,01553.330E,490.0m,3,210,,,,"Kat B 21/14  sourceAVS",,
"LANDL KatB_?",LANDL_B,AT,4735.330N,01202.910E,655.0m,3,230,350.0m,,,"Kat B -/23  Landerichtung SW, Feld steigt an, sehr enges Tal, keine normale Platzrunde, ersten 50m wellig unlanbar. sourceAVS",,
"LANGENWANG KatB_?",LANGEN_B,AT,4734.633N,01538.350E,642.0m,3,40,350.0m,,,"Kat B 04/22 Wiese suedlich der Strasse sehr uneben! sourceAVS",,
"LANGWIES KatB_?",LANGWI_B,AT,4746.219N,01343.259E,440.0m,3,40,300.0m,,,"Kat B 04/-   sourceAVS",,
"LENGAU KatB_?",LENGAU_B,AT,4722.300N,01232.277E,1140.0m,3,240,400.0m,,,"Kat B -/24  Anflug ueber 10 m hohe Baeume! sourceAVS",,
"LERMOOS KatB_?",LERMO_B,AT,4723.897N,01053.584E,970.0m,3,270,250.0m,,,"Kat B 270   Ost nach West zwischen zwei Stadeln ( 30 m Zwischenraum ), Laengsgraeben!!! sourceAVS",,
"LEUTASCH KatA_?",LEUTAS_A,AT,4722.590N,01109.809E,1110.0m,3,140,,,,"Kat A 14/32  sourceAVS",,
"LIEZEN KatB_?",LIEZEN_B,AT,4733.740N,01415.850E,635.0m,3,80,660.0m,,,"Kat B 08/26  sourceAVS",,
"LUDESCH KatA_?",LUDESC_A,AT,4711.250N,00946.250E,545.0m,3,40,350.0m,,,"Kat A 04/22  sourceAVS",,
"LUNZ AM SEE KatA_?",LUNZSE_A,AT,4750.781N,01501.124E,590.0m,3,30,450.0m,,,"Kat A 03/-   sourceAVS",,
"Madlig_?",ST,AT,4704.000N,01347.917E,1010.0m,3,220,300.0m,,,"DATI PROVENIENTI NON DAL CVAO. The data are not from CVAO. sourceAVS",,"N094E013_0016.jpg;N094E013_img288.jpg"
"MATHON KatA_?",MATHON_A,AT,4659.249N,01014.751E,1430.0m,3,70,280.0m,,,"Kat A 07/25 Bei Anflug aus West, Sportplatz mit hohem Zaun! sourceAVS",,
"MAYRHOFEN KatA_?",MAYRHO_A,AT,4710.816N,01152.169E,610.0m,3,10,570.0m,,,"Kat A 01/19 UL Platz, Querwege ueberrollbar sourceAVS",,
"MILS KatB_?",MILS_B,AT,4712.406N,01040.831E,730.0m,3,70,180.0m,,,"Kat B 07/-  Alle Querwege sind ueberrollbar! Wenn man das weiss, dann haben die 180m Laenge des offiziellen Landefeldes keinen Schrecken mehr! sourceAVS",,
"MITTERNDORF KatA_?",MITTDO_A,AT,4733.170N,01358.000E,820.0m,3,90,400.0m,,,"Kat A 09/27 Die anderen Wiesen um Mitterndorf sind stromleitungsverseucht oder uneben. sourceAVS",,
"MITTERRIEGEL KatA_?",MITRIE_A,AT,4806.615N,01600.990E,400.0m,3,30,280.0m,,,"Kat A 03/-   sourceAVS",,
"MITTERSILL-STUHLFELDEN KatB_?",MITTER_B,AT,4717.234N,01230.180E,780.0m,3,270,420.0m,,,"Kat B -/27   sourceAVS",,
"MOOSLANDL KatA_?",MOOSLA_A,AT,4738.761N,01446.061E,530.0m,3,350,,,,"Kat A -/35   sourceAVS",,
"MUENSTER-OST KatB_?",MUENST_B,AT,4725.798N,01150.688E,520.0m,3,10,500.0m,,,"Kat B 01/-  Landerichtung nur N, Feld steigt an sourceAVS",,
"MUERZZUSCHLAG KatB_?",MUERZZ_B,AT,4735.980N,01540.940E,780.0m,3,140,400.0m,,,"Kat B 14/-  Wiese steigt nach Sueden leicht an. sourceAVS",,
"MURAU KatA_?",MURAU_A,AT,4706.471N,01411.001E,800.0m,3,280,,,,"Kat A -/28   sourceAVS",,
"MURAU OST KatA_?",MURA-O_A,AT,4706.983N,01413.267E,777.0m,3,40,,,,"Kat A 04/22  sourceAVS",,"N094E014_0018.jpg;N094E014_img301.jpg"
"NASSEREITH NORD KatB_?",NASS_N_B,AT,4718.909N,01049.987E,835.0m,3,330,400.0m,,,"Kat B -/33  Leitung an der Landeschwelle ist schlecht sichtbar, da die Masten zwischen den Baeumen stehen! sourceAVS",,
"NASSEREITH SUED KatB_?",NASS_S_B,AT,4718.371N,01050.629E,835.0m,3,50,300.0m,,,"Kat B 05/-  Landerichtung O, Feld steigt an; Hochspannung macht 90 Knick wie eingezeichnet. sourceAVS",,
"NENZING KatB_?",NENZIN_B,AT,4711.488N,00941.850E,500.0m,3,110,150.0m,,,"Kat B 11/-   sourceAVS",,
"NEUBERG KatB_?",NEUBER_B,AT,4739.528N,01535.803E,720.0m,3,310,,,,"Kat B -/31  1 sourceAVS",,
"NEUWALD KatB_?",NEUWAL_B,AT,4744.865N,01530.988E,900.0m,3,310,400.0m,,,"Kat B -/31  Zwischen Goeller und Schneealpe, schlecht zu finden. Leitung im Anflug! sourceAVS",,
"NIEDERNSILL KatA_?",NIEDER_A,AT,4717.049N,01239.833E,767.0m,3,90,400.0m,,,"Kat A 09/27  sourceAVS",,
"NIEDERTHAI KatB_?",NITHAI_B,AT,4707.800N,01058.330E,1560.0m,3,40,300.0m,,,"Kat B 04/-   sourceAVS",,
"OBERAICH KatA_?",OBERAI_A,AT,4724.176N,01512.405E,500.0m,3,0,400.0m,,,"Kat A 00/00 Mehrere Moeglichkeiten sourceAVS",,
"OBERDORF KatA_?",OBERDO_A,AT,4728.146N,01507.284E,670.0m,3,90,400.0m,,,"Kat A 09/27  sourceAVS",,
"OBERORT-TRAGOESS KatB_?",OBEROR_B,AT,4731.959N,01504.292E,760.0m,3,90,280.0m,,,"Kat B 09/27  sourceAVS",,
"PACHER KatB_?",PACHER_B,AT,4726.469N,01545.119E,1050.0m,3,120,330.0m,,,"Kat B 12/-   sourceAVS",,
"PERNEGG KatB_?",PERNEG_B,AT,4721.311N,01520.671E,458.0m,3,340,400.0m,,,"Kat B -/34  Felder werden quer zur Landerichtung bebaut! sourceAVS",,
"PERNITZ NORD KatA_?",PERN-N_A,AT,4754.385N,01556.712E,440.0m,3,320,,,,"Kat A -/32   sourceAVS",,
"PERNITZ SUED KatA_?",PERN-S_A,AT,4753.220N,01557.270E,470.0m,3,270,,,,"Kat A -/27   sourceAVS",,
"PFANNHAMMER KatB_?",PFANNH_B,AT,4742.581N,01519.507E,794.0m,3,20,400.0m,,,"Kat B 02/-   sourceAVS",,
"PICHL PREUNEGG KatA_?",PICHL_A,AT,4723.129N,01337.213E,770.0m,3,280,500.0m,,,"Kat A -/28  Von Westen Leitung im Anflug! sourceAVS",,
"PRUTZ KatB_?",PRUTZ_B,AT,4705.083N,01040.083E,865.0m,3,330,400.0m,,,"Kat B -/33  Wiesen bei Toesens bevorzugen, Wassergraeben sourceAVS",,
"PUCHBERG KatA_?",PUCHBE_A,AT,4747.599N,01553.231E,615.0m,3,90,,,,"Kat A 09/27 Achtung Weidezaeune! sourceAVS",,
"PYHRN KatA_?",PYHRN_A,AT,4736.217N,01417.222E,825.0m,3,30,400.0m,,,"Kat A 03/-  Weidezaun am Wiesenanfang. sourceAVS",,
"RABENSTEIN KatA_?",RABENS_A,AT,4714.688N,01518.878E,410.0m,3,180,450.0m,,,"Kat A 18/-   sourceAVS",,
"RADFELD KatA_?",RADFEL_A,AT,4727.869N,01157.046E,511.0m,3,70,600.0m,,,"Kat A 07/25 Fallschirmspringer-Flugplatz sourceAVS",,
"Radstadt_?",SA,AT,4722.750N,01327.000E,830.0m,3,80,300.0m,,,"DATI PROVENIENTI NON DAL CVAO. The data are not from CVAO. sourceAVS",,
"RADSTADT KatA_?",RADSTA_A,AT,4722.900N,01327.867E,830.0m,3,70,,,,"Kat A 07/25  sourceAVS",,"N094E013_0012.jpg;N094E013_img262.jpg"
"RANTEN KatB_?",RANTEN_B,AT,4709.270N,01406.057E,900.0m,3,90,,,,"Kat B 09/27  sourceAVS",,
"REICHENFELS-OBDACH KatB_?",REICHE_B,AT,4700.450N,01445.050E,790.0m,3,160,170.0m,,,"Kat B 16/34 Sommer 2004 noerdlicher Teil Kornfeld! sourceAVS",,
"REIN KatA_?",REIN_A,AT,4708.200N,01517.470E,443.0m,3,260,450.0m,,,"Kat A -/26   sourceAVS",,
"REITDORF KatA_?",REITDO_A,AT,4722.420N,01323.180E,875.0m,3,320,400.0m,,,"Kat A -/32  Landung nur Richtung Nordwest, auf Hochspannungsleitung achten! sourceAVS",,
"RESCHEN KatB_?",RESCHE_B,AT,4651.793N,01030.665E,1420.0m,3,10,200.0m,,,"Kat B 01/-  Telefonleitung im Anflug und Graben am Anfang der Wiese! sourceAVS",,
"RETTENBACH KatB_?",RETTEN_B,AT,4716.852N,01227.131E,795.0m,3,40,350.0m,,,"Kat B 04/-  Anflug ueber Stasse und Zaun! sourceAVS",,
"ROHR-IM-GEBI KatB_?",ROHR_B,AT,4753.121N,01545.140E,680.0m,3,320,,,,"Kat B -/32   sourceAVS",,
"ROTMOOS KatB_?",ROTMOO_B,AT,4741.045N,01509.560E,690.0m,3,300,380.0m,,,"Kat B -/30  Im Anflug auf der linken Seite halten und zwischen die beiden linken Stadeln die am Ende der Wiese stehen zielen. sourceAVS",,
"SAALFELDEN KatA_?",SAALFE_A,AT,4726.283N,01250.862E,755.0m,3,340,300.0m,,,"Kat A -/34   sourceAVS",,
"SCHARNITZ KatB_?",SCHARN_B,AT,4723.176N,01115.041E,970.0m,3,70,500.0m,,,"Kat B 07/25 viele Leitungen beachten! sourceAVS",,
"SCHLITTERS KatA_?",SCHLIT_A,AT,4722.334N,01150.745E,530.0m,3,150,320.0m,,,"Kat A 15/33 Bewuchsgrenzen ueberrollbar sourceAVS",,
"SCHNEPFAU KatA_?",SCHNEP_A,AT,4720.882N,00956.050E,700.0m,3,90,500.0m,,,"Kat A 09/27  sourceAVS",,
"SCHOEDER KatB_?",SCHOED_B,AT,4711.150N,01407.583E,870.0m,3,60,,,,"Kat B 06/24  sourceAVS",,"N094E014_0017.jpg;N094E014_img298.jpg"
"SCHRUNS KatB_?",SCHRUN_B,AT,4704.406N,00955.212E,680.0m,3,40,200.0m,,,"Kat B 04/22 Schwieriger Anflug durch Hochspannung und Haeuser! sourceAVS",,
"SCHWARZAU KatB_?",SCHWA_B,AT,4750.573N,01541.772E,645.0m,3,10,350.0m,,,"Kat B 01/19  sourceAVS",,
"SCHWAZ KatA_?",SCHWAZ_A,AT,4721.567N,01143.583E,531.0m,3,40,1000.0m,,,"Kat A 04/22  sourceAVS",,"N094E011_0008.jpg"
"SPITAL-SEMMERING KatB_?",SPITAL_B,AT,4736.725N,01544.745E,755.0m,3,50,,,,"Kat B 05/-   sourceAVS",,
"SPITZWIESEN KatA_?",SPITZW_A,AT,4649.840N,01406.000E,805.0m,3,50,500.0m,,,"Kat A 05/23  sourceAVS",,
"ST-AEGYD KatA_?",ST-AEG_A,AT,4751.133N,01533.250E,645.0m,3,290,800.0m,,,"Kat A -/29  Flugzeugtraegerlandung, Bodenwellen, ev. Weidezaeune! sourceAVS",,
"STAMS KatA_?",STAMS_A,AT,4716.928N,01059.383E,635.0m,3,70,300.0m,,,"Kat A 07/25  sourceAVS",,
"STANZACH KatA_?",STANZA_A,AT,4722.736N,01033.734E,960.0m,3,140,300.0m,,,"Kat A 14/-  Landerichtung SO, Feld steigt an. sourceAVS",,
"STEIN-ENNSTAL KatA_?",STEIN_A,AT,4726.650N,01357.200E,660.0m,3,40,,,,"Kat A 04/22  sourceAVS",,
"ST-JAKOB IN HAUS KatB_?",ST-JAK_B,AT,4729.985N,01233.974E,856.0m,3,160,400.0m,,,"Kat B 16/-   sourceAVS",,
"ST-JOHANN-PO KatA_?",ST-J-P_A,AT,4721.750N,01312.183E,560.0m,3,360,390.0m,,,"Kat A -/36  Landung Richtung Norden, Anflug ueber Sportplatz sourceAVS",,"N094E013_0011.jpg;N094E013_img256.jpg;N094E013_img259.jpg"
"ST-MAREIN KatA_?",ST-MAR_A,AT,4728.790N,01522.780E,540.0m,3,240,700.0m,,,"Kat A -/24   sourceAVS",,
"STOJEN KatB_?",STOJEN_B,AT,4739.475N,01539.140E,750.0m,3,90,320.0m,,,"Kat B 09/-   sourceAVS",,
"ST-OSWALD KatA_?",ST-OSW_A,AT,4716.378N,01430.241E,945.0m,3,10,,,,"Kat A 01/-   sourceAVS",,
"STRASS-ZILLERTAL KatB_?",STRASS_B,AT,4724.040N,01149.246E,524.0m,3,60,300.0m,,,"Kat B 06/-  Leitung teilt Feld in Ost/Westrichtung, Achtung 2. Leitung! sourceAVS",,
"ST-ULRICH KatB_?",ST-ULR_B,AT,4730.851N,01235.089E,860.0m,3,80,280.0m,,,"Kat B 08/-  Anflug ueber grosses Hotel und Quer-Baumreihe! Queranflug an den westlichen Hang anlehnen ! sourceAVS",,
"STUPPACH KatA_?",STUPPA_A,AT,4741.030N,01558.460E,420.0m,3,60,520.0m,,,"Kat A 06/24  sourceAVS",,
"TECHENDORF KatB_?",TECHEN_B,AT,4642.670N,01317.950E,935.0m,3,150,290.0m,,,"Kat B 15/-   sourceAVS",,
"TERNITZ KatA_?",TERNIT_A,AT,4742.500N,01601.000E,398.0m,3,40,,,,"Kat A 04/-   sourceAVS",,
"THALHAMM KatB_?",THALHA_B,AT,4726.023N,01354.408E,670.0m,3,90,,,,"Kat B 09/27  sourceAVS",,
"TIENZENS-STATZ KatB_?",TIENZE_B,AT,4706.656N,01127.622E,1115.0m,3,330,260.0m,,,"Kat B -/33  Flugplatz Innsbruck liegt 19 km entfernt und ist 600m tiefer. sourceAVS",,
"TOESENS NORD KatA_?",TOES-N_A,AT,4701.465N,01037.028E,905.0m,3,40,470.0m,,,"Kat A 04/22  sourceAVS",,
"TOESENS SUED KatA_?",TOES-S_A,AT,4700.317N,01035.717E,930.0m,3,30,350.0m,,,"Kat A 03/21 Mit  Stein-Mauern  gebildete Absaetze beachten! sourceAVS",,"N094E010_0005.jpg;N094E010_img218.jpg"
"TUMPEN OETZTAL KatB_?",TUMPEN_B,AT,4710.054N,01054.699E,930.0m,3,180,500.0m,,,"Kat B 18/36 Viele ca. 50 cm lange Begrenzungs-Stempen! Hochspannungsleitungen! sourceAVS",,
"UMHAUSEN OETZTAL KatB_?",UMHAUS_B,AT,4707.743N,01055.577E,1075.0m,3,160,450.0m,,,"Kat B 16/-  Wiese steigt maessig steil von Nord nach Sued an! sourceAVS",,
"UNTERTRIESTING KatB_?",UNTERT_B,AT,4801.925N,01555.365E,450.0m,3,340,350.0m,,,"Kat B -/34   sourceAVS",,
"URREITING (ST-JOHANN) KatB_?",URREIT_B,AT,4722.373N,01312.943E,555.0m,3,180,500.0m,,,"Kat B 18/36 Alternative zu St. Johann i.P. sourceAVS",,
"URSPRUNG KatB_?",URSPRU_B,AT,4736.600N,01201.000E,830.0m,3,350,200.0m,,,"Kat B -/35  Enges Tal keine normale Platzrunde moeglich. sourceAVS",,
"UTTENDORF KatB_?",UTTEND_B,AT,4717.224N,01233.244E,790.0m,3,10,340.0m,,,"Kat B 01/-  Landerichtung Nord sourceAVS",,
"VIEHHOFEN KatB_?",VIEHHO_B,AT,4721.972N,01242.906E,880.0m,3,280,470.0m,,,"Kat B -/28  Der Querweg ist ueberrollbar! sourceAVS",,
"VILS KatB_?",VILS_B,AT,4732.890N,01038.700E,825.0m,3,90,470.0m,,,"Kat B 09/-  Sehr schmal. sourceAVS",,
"VOMP-MOORHOF KatA_?",VOMP_A,AT,4719.816N,01141.318E,541.0m,3,140,200.0m,,,"Kat A 14/32 Mehrere Moeglichkeiten sourceAVS",,
"WALCHSEE KatB_?",WALCHS_B,AT,4738.480N,01217.450E,690.0m,3,80,330.0m,,,"Kat B 08/-   sourceAVS",,
"WEINBACH KatA_?",WEINBA_A,AT,4742.850N,01331.800E,525.0m,3,100,800.0m,,,"Kat A 10/28  sourceAVS",,"N095E013_0004.jpg"
"WEISSBACH KatB_?",WEISSB_B,AT,4731.567N,01244.517E,660.0m,3,320,360.0m,,,"Kat B -/32  sehr enges Tal, keine Platzrunde moeglich. sourceAVS",,"N095E012_img206.jpg"
"WENIGZELL KatB_?",WENIGZ_B,AT,4725.515N,01547.684E,790.0m,3,300,,,,"Kat B -/30   sourceAVS",,
"WESTENDORF KatB_?",WESTEN_B,AT,4725.722N,01212.991E,800.0m,3,100,400.0m,,,"Kat B 10/-  Wiese steigt nach SO an, Hangauflandung sourceAVS",,
"WINDISCHGARSTEN NORD KatA_?",WIND-N_A,AT,4744.126N,01419.465E,620.0m,3,70,500.0m,,,"Kat A 07/-   sourceAVS",,
"WINDISCHGARSTEN SUED KatB_?",WIND-S_B,AT,4742.390N,01418.919E,590.0m,3,310,650.0m,,,"Kat B -/31   sourceAVS",,
"WOERGL KatA_?",WOERGL_A,AT,4729.280N,01205.330E,520.0m,3,100,480.0m,,,"Kat A 10/28 asphaltierter Querweg im Osten ueberrollbar sourceAVS",,
"WOERTH-RAURIS KatA_?",WOERTH_A,AT,4711.940N,01258.848E,960.0m,3,80,300.0m,,,"Kat A 08/-   sourceAVS",,
"WUERFLACH KatA_?",WUERFL_A,AT,4746.719N,01604.359E,380.0m,3,60,700.0m,,,"Kat A 06/24  sourceAVS",,
"ZAMS KatB_?",ZAMS_B,AT,4709.300N,01034.825E,770.0m,3,110,200.0m,,,"Kat B 11/29  sourceAVS",,
"ZELLER RAIN KatB_?",ZELLER_B,AT,4747.684N,01512.341E,1067.0m,3,120,300.0m,,,"Kat B 12/-   sourceAVS",,
"ALTDORF KatB_?",ALTDOR_B,CH,4652.816N,00837.516E,444.0m,3,0,,,,"Kat B  sourceAVS",,
"ALVANEU-BAD KatB_?",ALVANE_B,CH,4640.200N,00939.600E,970.0m,3,0,,,,"Kat B  sourceAVS",,
"ANDEER KatB_?",ANDEER_B,CH,4636.572N,00925.637E,980.0m,3,10,300.0m,,,"Kat B 01/19 Gelaendestufe und Querfelder! sourceAVS",,
"ANDERMATT KatA_?",ANDERM_A,CH,4637.733N,00835.050E,1430.0m,3,50,300.0m,,,"Kat A 05/23 Haenge mit Transportkabeln verseucht!Auf Unebenheiten und Bewuchsuebergaenge achten! sourceAVS",,
"BAUMA KatB_?",BAUMA_B,CH,4722.366N,00851.883E,640.0m,3,0,,,,"Kat B  sourceAVS",,
"BENNAU KatA_?",BENNAU_A,CH,4708.600N,00842.383E,900.0m,3,0,,,,"Kat A  sourceAVS",,
"BUETSCHWIL KatA_?",BUETSC_A,CH,4722.151N,00904.065E,620.0m,3,170,400.0m,,,"Kat A 17/35  sourceAVS",,
"CHARRAT KatA_?",CHARRA_A,CH,4607.080N,00707.470E,459.0m,3,60,300.0m,,,"Kat A 06/24  sourceAVS",,
"CUNTERS KatB_?",CUNTER_B,CH,4636.800N,00935.229E,1210.0m,3,20,200.0m,,,"Kat B 02/-   sourceAVS",,
"DAVOS SEE KatB_?",DAVOSS_B,CH,4648.828N,00950.901E,1560.0m,3,0,,,,"Kat B Achtung: Fussgaenger und Kinder!Leicht gebogener Anflug ueber den See. sourceAVS",,
"DISENTIS KatB_?",DISENT_B,CH,4642.183N,00851.433E,1150.0m,3,220,250.0m,,,"Kat B -/22  Alle Wiesen ca. 3% Gefaelle sourceAVS",,
"EBNAT-KAPPEL KatA_?",EBNAT_A,CH,4716.233N,00906.616E,630.0m,3,160,400.0m,,,"Kat A 16/34  sourceAVS",,
"EINSIEDELN KatA_?",EINSIE_A,CH,4706.683N,00843.750E,910.0m,3,0,,,,"Kat A  sourceAVS",,
"FISCHENTHAL KatA_?",FISCHE_A,CH,4719.566N,00855.183E,750.0m,3,0,,,,"Kat A  sourceAVS",,
"FLUEELEN KatB_?",FLUEEL_B,CH,4653.250N,00836.733E,440.0m,3,0,,,,"Kat B  sourceAVS",,
"FRAUENKIRCH KatB_?",FRAUEN_B,CH,4646.582N,00948.441E,1510.0m,3,30,300.0m,,,"Kat B 03/21 Sehr enges Tal, keine normale Platzrunde moeglich!Die beiden Hindernisse koennen NICHT durchflogen werden! sourceAVS",,
"FREIENBACH KatB_?",FREIEN_B,CH,4712.120N,00845.830E,410.0m,3,0,,,,"Kat B  sourceAVS",,
"FULDERA KatB_?",FULDER_B,CH,4636.850N,01021.717E,1640.0m,3,140,300.0m,,,"Kat B 14/32 Auf Wassergraeben achten ! (Gepunktete Linien ! ) sourceAVS",,"N093E010_0040.jpg;N093E010_img444.jpg"
"GONTEN KatB_?",GONTEN_B,CH,4719.353N,00920.466E,926.0m,3,40,250.0m,,,"Kat B 04/22 im Suedteil leicht wellig, zwei Pfosten, die auf den Foto von oben erkennbaren anderen Wiesen sind von Pfosten  sourceAVS",,
"IBACH NORD KatB_?",IBACHN_B,CH,4700.883N,00837.750E,460.0m,3,0,,,,"Kat B  sourceAVS",,
"IBACH SUED KatB_?",IBACHS_B,CH,4700.500N,00838.466E,460.0m,3,0,,,,"Kat B  sourceAVS",,
"ILANZ KatB_?",ILANZ_B,CH,4646.526N,00913.111E,720.0m,3,90,300.0m,,,"Kat B 09/27  sourceAVS",,
"JENAZ KatB_?",JENAZ_B,CH,4656.616N,00942.450E,750.0m,3,170,300.0m,,,"Kat B 17/35 Enges Tal, Gelaendestufen! sourceAVS",,
"KLOSTERS KatA_?",KLOSTE_A,CH,4651.738N,00954.014E,1210.0m,3,40,450.0m,,,"Kat A 04/22 Viehweiden, Zaeune sind moeglich!!! sourceAVS",,
"LANGNAU KatA_?",LANGNA_A,CH,4656.116N,00748.150E,680.0m,3,0,,,,"Kat A  sourceAVS",,
"LAUERZERSEE KatA_?",LAUERZ_A,CH,4702.350N,00836.066E,470.0m,3,0,,,,"Kat A  sourceAVS",,
"LAVIN KatB_?",LAVIN_B,CH,4646.130N,01007.380E,1450.0m,3,90,350.0m,,,"Kat B 09/00 Enges V-Tal, Anflug ueber Inn-Terrassen-Boeschung, Bewaesserungsstangen beachten; sourceAVS",,
"MALOJA CASAC KatB_?",MALOJC_B,CH,4623.209N,00939.759E,1450.0m,3,20,,,,"Kat B 02/-   sourceAVS",,
"MARBACH KatB_?",MARBAC_B,CH,4652.033N,00754.316E,830.0m,3,0,,,,"Kat B  sourceAVS",,
"Mendrisio_?",MEND_?,CH,4553.169N,00858.659E,290.0m,3,180,300.0m,,,"Fili Alta tensione. prato (ACAO) sourceAVS",,
"PFAEFFIKON KatA_?",PFAEFF_A,CH,4712.350N,00847.500E,410.0m,3,0,,,,"Kat A  sourceAVS",,
"RAMOSCH KatB_?",RAMOSC_B,CH,4649.967N,01023.033E,1230.0m,3,260,400.0m,,,"Kat B -/26  Terrasse, schwierige Landeeinteilung sourceAVS",,"N093E010_0113.jpg;N093E010_img917.jpg"
"RHAEZUENS KatA_?",RHAEZU_A,CH,4648.398N,00924.410E,650.0m,3,20,500.0m,,,"Kat A 02/20  sourceAVS",,
"ROTHENBRUNNEN KatA_?",ROTHEN_A,CH,4644.530N,00925.720E,630.0m,3,180,400.0m,,,"Kat A 18/36 Baumreihe im Anflug sourceAVS",,
"SAGOGN KatA_?",SAGOGN_A,CH,4647.333N,00915.500E,770.0m,3,90,450.0m,,,"Kat A 09/27  sourceAVS",,
"SALAND KatA_?",SALAND_A,CH,4723.516N,00851.416E,600.0m,3,0,,,,"Kat A  sourceAVS",,
"SAVOGNIN KatB_?",SAVOGN_B,CH,4635.530N,00936.150E,1200.0m,3,140,250.0m,,,"Kat B 14/32 Viele Hindernisse, schwieriges Feld! sourceAVS",,
"SCHAIVEL KatB_?",SCHAIV_B,CH,4637.919N,01027.050E,1260.0m,3,50,170.0m,,,"Kat B 05/-  Sehr kurz, Bewaesserungsstangen beachten! sourceAVS",,
"SCHIERS KatB_?",SCHIER_B,CH,4658.544N,00939.990E,620.0m,3,120,350.0m,,,"Kat B 12/30 Enges Tal, behindert Anflug aus dem Westen! sourceAVS",,
"SCHUEPFHEIMN KatA_?",SCHUEN_A,CH,4657.680N,00801.230E,700.0m,3,0,,,,"Kat A  sourceAVS",,
"SCHUEPFHEIMW KatA_?",SCHUEW_A,CH,4656.216N,00759.500E,750.0m,3,0,,,,"Kat A  sourceAVS",,
"SCHULS-PRADELLA KatB_?",SCHU-P_B,CH,4648.180N,01019.760E,1170.0m,3,90,350.0m,,,"Kat B 09/-  Hanglandung, im engen Tal! sourceAVS",,
"SEDRUN KatB_?",SEDRUN_B,CH,4640.666N,00846.933E,1400.0m,3,330,300.0m,,,"Kat B -/33  Flugzeugtraegerlandung, Seilbahn suedlich der Wiese! sourceAVS",,
"SILS KatA_?",SILS_A,CH,4625.979N,00946.209E,1800.0m,3,60,400.0m,,,"Kat A 06/24 Gut sichtbarer Stahlpfosten! sourceAVS",,
"SURAVA KatB_?",SURAVA_B,CH,4639.808N,00936.995E,905.0m,3,190,200.0m,,,"Kat B -/19   sourceAVS",,
"SUSCH KatB_?",SUSCH_B,CH,4644.650N,01004.870E,1430.0m,3,210,350.0m,,,"Kat B -/21  Enges Tal, Anflug schwierig. sourceAVS",,
"THUSIS KatA_?",THUSIS_A,CH,4642.692N,00926.750E,670.0m,3,340,250.0m,,,"Kat A -/34  Am alten Feld wurde eine Raststaette errichtet! Wege sind teilweise ueberrollbar. sourceAVS",,
"TRUB KatB_?",TRUB_B,CH,4656.283N,00752.283E,780.0m,3,0,,,,"Kat B  sourceAVS",,
"WAEDENSWIL OST KatA_?",WAED_O_A,CH,4713.483N,00839.166E,580.0m,3,0,,,,"Kat A  sourceAVS",,
"WAEDENSWIL WESR KatA_?",WAED_W_A,CH,4713.850N,00838.116E,580.0m,3,0,,,,"Kat A  sourceAVS",,
"WALENSTADT KatA_?",WALENS_A,CH,4707.033N,00918.533E,420.0m,3,0,,,,"Kat A  sourceAVS",,
"WATTWIL KatB_?",WATTWI_B,CH,4716.816N,00906.016E,620.0m,3,160,300.0m,,,"Kat B 16/34 Ebnat-Kappel ist die bessere Wahl! sourceAVS",,
"WEESEN KatA_?",WEESEN_A,CH,4707.433N,00906.100E,420.0m,3,0,,,,"Kat A  sourceAVS",,
"WIMMIS KatB_?",WIMMIS_B,CH,4639.833N,00736.200E,650.0m,3,0,,,,"Kat B  sourceAVS",,
"ZELL KatA_?",ZELL_A,CH,4726.800N,00849.004E,530.0m,3,0,,,,"Kat A leichte Hanglandung sourceAVS",,
"ZERNEZ KatA_?",ZERNEZ_A,CH,4641.533N,01005.600E,1470.0m,3,80,500.0m,,,"Kat A 08/26  sourceAVS",,"N093E010_0114.jpg;N093E010_img922.jpg"
"ZIGNAU KatB_?",ZIGNAU_B,CH,4644.650N,00900.730E,840.0m,3,100,400.0m,,,"Kat B 10/28 Enges Tal, Hindernisse im Anflug! sourceAVS",,
"ZUOZ-S-CHANF KatA_?",ZUOZ-S_A,CH,4635.976N,00957.974E,1660.0m,3,40,400.0m,,,"Kat A 04/22 Alternatives Feld sued-oestlich der Strasse ist eine Golfplatz-Driving-Range! Die Golfbaelle fliegen! sourceAVS",,
"AURACH KatB_?",AURACH_B,DE,4741.990N,01155.465E,800.0m,3,180,450.0m,,,"Kat B 18/-  Landerichtung S, Feld steigt an; Fahrweg ist nicht ueberrollbar! Den westlichen Teil der Wiese benutzen, weil der oestliche Teil wellig ist! sourceAVS",,
"BAYRISCHZELL KatA_?",BAYRIS_A,DE,4740.074N,01201.014E,800.0m,3,170,500.0m,,,"Kat A 17/35 Nr 2: weg ueberrollbar sourceAVS",,
"BOSCHHOF KatA_?",BOSCHH_A,DE,4748.428N,01125.145E,600.0m,3,90,250.0m,,,"Kat A 09/27  sourceAVS",,
"DUERNBACH KatA_?",DUERNB_A,DE,4746.070N,01143.978E,749.0m,3,170,300.0m,,,"Kat A 17/35  sourceAVS",,
"FALL-SYLVENS KatA_?",FALL_A,DE,4734.241N,01132.963E,780.0m,3,160,300.0m,,,"Kat A 16/-  Landung Richtung Sueden, erst in zweiter Haelfte nach Querweg aufsetzen. sourceAVS",,
"FARCHANT NORD KatB_?",FARCHA_B,DE,4732.227N,01106.886E,671.0m,3,30,250.0m,,,"Kat B 03/21 Wiese an der Strasse bevorzugt, auf 2m breite Wassergraeben achten! sourceAVS",,
"FARCHANT SUED KatB_?",FARCHS_B,DE,4731.385N,01106.508E,680.0m,3,180,460.0m,,,"Kat B 18/36 Bei Anflug von Sued nach Nord Quer-Bodenwelle! sourceAVS",,
"FISCHBACHAU KatB_?",FISCHB_B,DE,4743.239N,01156.662E,760.0m,3,140,420.0m,,,"Kat B 14/-  Gelaende steigt nach Osten an! sourceAVS",,
"FISCHHAUSEN KatB_?",FISCHH_B,DE,4742.549N,01152.148E,800.0m,3,140,250.0m,,,"Kat B 14/-  Achtung, neuer Pferdezaun! Leicht ansteigend Richtung SO. Bei Endanflug aus Sueden muss 4 km vorher der Spitzingsattel (1150m) ueberflogen werden! Achtung, neuer Pferdezaun! sourceAVS",,
"GARMISCH OST KatB_?",GARMIO_B,DE,4729.008N,01105.927E,730.0m,3,140,340.0m,,,"Kat B 14/-  Landerichtung nur S, Feld steigt an sourceAVS",,
"GARMISCH WEST KatB_?",GARMIW_B,DE,4728.264N,01103.245E,745.0m,3,50,300.0m,,,"Kat B 05/23  sourceAVS",,
"GROSSPIENZENAU-THALHAM KatB_?",GROSSP_B,DE,4749.384N,01149.792E,700.0m,3,150,400.0m,,,"Kat B 15/-  Feld ist unterteilt durch Zaeune; landerichtung S, Feld steigt an; sourceAVS",,
"HAUSHAM KatA_?",HAUSHA_A,DE,4744.751N,01150.804E,740.0m,3,140,700.0m,,,"Kat A 14/-  Wiese steigt leicht von Nord nach Sued an. sourceAVS",,
"HUNDHAM KatA_?",HUNDHA_A,DE,4745.267N,01156.585E,780.0m,3,140,400.0m,,,"Kat A 14/-  noerdlicher Variante besser, Suedliche Wiese: Landung nur nach Sued, Feld steigt an. sourceAVS",,
"JACHENAU KatA_?",JACHEN_A,DE,4736.453N,01129.523E,750.0m,3,70,500.0m,,,"Kat A 07/25  sourceAVS",,
"KOCHEL KatA_?",KOCHEL_A,DE,4740.330N,01121.249E,599.0m,3,150,250.0m,,,"Kat A 15/33  sourceAVS",,
"KRUEN KatA_?",KRUEN_A,DE,4730.594N,01115.966E,900.0m,3,140,400.0m,,,"Kat A 14/32 Mehrere Moeglichkeiten! Im Anflug von Ost nach West Hochspannung beachten! sourceAVS",,
"LENGGRIES KatA_?",LENGGR_A,DE,4740.899N,01133.588E,700.0m,3,270,250.0m,,,"Kat A -/27  Querweg ueberrollbar! sourceAVS",,
"MITTENWALD KatB_?",MITTEN_B,DE,4725.098N,01115.528E,912.0m,3,10,548.0m,,,"Kat B 01/19 Enges Tal, keine normale Platzrunde moeglich. sourceAVS",,
"REIT-IM-WINK KatA_?",REITIW_A,DE,4740.426N,01228.663E,695.0m,3,360,200.0m,,,"Kat A -/36   sourceAVS",,
"ROTTACH-EGERN KatA_?",ROTTAC_A,DE,4740.957N,01148.139E,750.0m,3,90,300.0m,,,"Kat A 09/27 Suedlichen Wiesen leicht ansteigend Richtung Osten. sourceAVS",,
"SCHARLING KatB_?",SCHARL_B,DE,4740.143N,01144.776E,760.0m,3,270,300.0m,,,"Kat B -/27  Beste variante Nr 1: Landerichtung W, Feld steigt an; sourceAVS",,
"UNTERAMMERGAU KatA_?",UNTERA_A,DE,4737.450N,01101.900E,840.0m,3,10,250.0m,,,"Kat A 01/19  sourceAVS",,
"UNTERBUCHEN KatA_?",UNTERB_A,DE,4746.911N,01129.170E,632.0m,3,180,300.0m,,,"Kat A 18/36 Hochspannungsleitung oestlich der Strasse! sourceAVS",,
"WACKERSBERG KatA_?",WACKER_A,DE,4744.062N,01133.115E,730.0m,3,90,400.0m,,,"Kat A 09/27  sourceAVS",,
"WEGSCHEID KatA_?",WEGSCH_A,DE,4739.850N,01134.250E,700.0m,3,270,200.0m,,,"Kat A -/27   sourceAVS",,
"WERTACH KatB_?",WERTAC_B,DE,4736.200N,01025.100E,890.0m,3,320,400.0m,,,"Kat B -/32  Leitungen im Anflug. Einzelwiesen, nach Bewuchs waehlen, dazwischen Pfaehle und Zaeune! sourceAVS",,
"TANINGES KatA_?",TANING_A,FR,4606.000N,00636.000E,625.0m,3,90,300.0m,,,"Kat A 09/27  sourceAVS",,
"Auronzo KatB_4",Auronz_4,IT,4633.900N,01224.383E,830.0m,3,130,160.0m,,,"Ce ne sono 2. Uno spesso occupato, l'altro cortissimo e stretto Kat B 13/31 Sehr kurz! sourceAVS e webinar",,"N093E012_0044.jpg;N093E012_img471.jpg"
"Baldissero_8?",Baldi_8?,IT,4446.568N,00752.756E,310.0m,3,130,300.0m,,,"sourceAVS, confermato da seeyou",,
"campari_?",camp_?,IT,4604.945N,00816.518E,230.0m,3,0,200.0m,,,"verif coordinate (ACAO) sourceAVS",,
"farra-d-soli KatA_?",FARRA_A,IT,4554.000N,01208.033E,160.0m,3,340,300.0m,,,"Kat A -/34   sourceAVS",,"N091E012_0079.jpg;N091E012_img697.jpg;N091E012_img700.jpg"
"fondotoce_?",OVBTOCE,IT,4556.783N,00828.857E,195.0m,3,0,200.0m,,,"Tanti campi scegliere in base alle coltivazioni (ACAO) sourceAVS",,
"forestale_6",Foresale6,IT,4611.450N,01207.183E,467.0m,3,0,,,,"se molto bassi usendo dall'agordino. Recupero difficoltoso  sourceAVS",,
"fornasette_?",forn_avs,IT,4600.008N,00847.619E,393.0m,3,0,200.0m,,,"ATTERR SUD! In svizzera piantonamento! (ACAO) sourceAVS",,
"imer_?",IMER,IT,4608.800N,01147.700E,640.0m,3,70,450.0m,,,"sourceAVS",,"N000W001_0075.jpg;N092E011_img672.jpg;N092E011_img675.jpg"
"maseera_?",mase_?,IT,4519.450N,01152.350E,9.0m,3,180,180.0m,,,"sourceAVS",,
"mesenzana_?",menz_?,IT,4558.639N,00844.707E,219.0m,3,0,200.0m,,,"Facile. attenz ai fossi ai margini (ACAO) sourceAVS",,
"niederdorf KatB_?",NIEDRD_B,IT,4644.200N,01209.350E,1150.0m,3,100,300.0m,,,"Kat B 10/28  sourceAVS",,
"pinzolo_?",pinz_?,IT,4608.283N,01045.600E,710.0m,3,10,300.0m,,,"SUFF ingr N verso S tenere la DX toccare dopo stradina che arriva da est sourceAVS",,
"preval KatA_?",PREVAL_A,IT,4557.380N,01332.183E,55.0m,3,90,400.0m,,,"Kat A 09/27  sourceAVS",,
"sgervasoul_?",gerv_?,IT,4537.756N,00931.239E,230.0m,3,180,200.0m,,,"ULM attenz alta tensione testata N. ingresso a 0 da S sourceAVS",,
"st-leonhard KatB_?",ST-LEO_B,IT,4648.324N,01114.498E,640.0m,3,20,300.0m,,,"Kat B 02/-  Achtung Bewaesserungsstangen, Anflug ueber Bauernhof! sourceAVS",,
"susa KatA_?",SUSA_A,IT,4506.750N,00717.230E,380.0m,3,90,350.0m,,,"Kat A 09/27 Talwind kommt meist aus Osten. sourceAVS",,
"vigili bl_?",Vigil_??,IT,4607.833N,01204.883E,328.0m,3,210,300.0m,,,"sourceAVS",,"N000W001_VIGILI_BL_SK.jpg;N000W001_VIGILI_BL_1.png"
"dolenja vas KatB_?",DOLENJ_B,SI,4612.583N,01413.433E,420.0m,3,310,250.0m,,,"Kat B -/31   sourceAVS",,
"jezersko katb_?",JEZERS_B,SI,4624.300N,01430.483E,880.0m,3,10,300.0m,,,"Kat B 01/-  Schwer aus der Luft zu finden! sourceAVS",,"N092E014_0052.jpg;N092E014_img517.jpg"
"logarska katb_?",LOGARS_B,SI,4625.000N,01438.500E,810.0m,3,20,300.0m,,,"Kat B 02/20 Tal ist extrem eng, keine Platzrunde moeglich. sourceAVS",,
"Cervens Route_ul8 ",Cerv_ul8,FR,4617.602N,00626.752E,606.0m,2,50,300.0m,,,"san:added",,
"Coustellet_UL8",Cous_UL8,FR,4352.156N,00509.496E,115.0m,2,100,300.0m,,,"san:added",,
"Aiton_7",723L_7,FR,4533.533N,00614.050E,300.0m,3,110,300.0m,,,"Page 222: Large flat area. High crops. Sudden wind changes. Power lines N/S. S of road marked fields",,
"Aix en Diois_ZA7",512L_ZA7,FR,4441.383N,00524.500E,500.0m,3,150,300.0m,,"130.000","Page 180: 300m Crops. Choose field. Private airfield in area - see landout book. (not sure if Freq 130.0 is right)",,
"ALBERTVILLE_9",LFKA_9,FR,4537.567N,00619.717E,316.0m,5,230,800.0m,,"123.500","Page 66: Circuit to NW.",,
"Ampus_7",231L_7,FR,4337.100N,00621.050E,625.0m,3,60,300.0m,,,"Page 129: 300m Crop (shown NE-SW) Cables nr Road",,
"ANNECY_A",LFLP_A,FR,4555.800N,00605.983E,464.0m,5,22,1300.0m,,"118.200","Page 56: App 121.200 above 3500. Twr 118.200. FIS 123.700",,
"ANNEMASSE_A",LFLI_A,FR,4611.500N,00616.100E,493.0m,5,120,1300.0m,,"125.870","Page 52:",,
"Artignosc_9",211S_9,FR,4341.083N,00608.100E,580.0m,3,70,550.0m,,,"Page 109: Private airfield. Grass. Slight slope up to NE.",,
"ASPRES_9",LFNJ_9,FR,4431.067N,00544.167E,839.0m,4,360,895.0m,,"123.500","Page 22: Gliding 18/36 Circuit W or 10/28 Circuit S. Do not land in N Wind go to Serre.",,
"AUBENASSON_9",LFJF_9,FR,4441.717N,00509.033E,250.0m,2,90,700.0m,,"123.500","Page 50: 09/27 700m 123.50 Grass unmarked strip.Circuit to S.",,
"Aups_8",213L_8,FR,4337.583N,00610.817E,450.0m,3,130,300.0m,,,"Page 111: Landing zone. 300m Crop. Choose a Field. (shown is NW-SE)",,
"AVIGNON_A",LFNT_A,FR,4359.767N,00445.267E,45.0m,2,160,1350.0m,,"123.350","Page 6: Call Orange Approach 118.925. Gliders on shorter runway to east (16L/34R) or 12/30. Power on 16R/34L",,
"Banon_7",127M_7,FR,4404.000N,00540.000E,770.0m,3,270,300.0m,,,"Page 99: Possible landing zone. Caution - a lot of lavender. Two areas - see landout book.",,
"BARCELONNETTE_A",LFMR_A,FR,4423.233N,00636.550E,1142.0m,4,90,800.0m,,"123.500","Page 40: Gliding. A/T. Circuit S. Domed runway. Turbulent in strong W wind.",,
"Barreme_5",332D_5,FR,4359.600N,00623.167E,780.0m,3,10,300.0m,,,"Page 158: 01/19 300m Grass. Lots of ditches to inspect on foot first.Downwind East. Pref land to North. Markers at southern edge field",,
"Bathie_6",722L_6,FR,4537.533N,00626.617E,375.0m,3,160,200.0m,,,"Page 220: 16/34 400m. Crops. Land Parallel to Road in one half. Touch down and taxi within the width of one field only. Short.",,
"Bauden_7",212L_7,FR,4341.050N,00612.917E,710.0m,3,130,500.0m,,,"Page 110: Choose field according to crops.",,
"Bayon_6",320DD_5,FR,4420.233N,00609.867E,860.0m,3,360,220.0m,,,"Page 146: Meadows. Difficult landing",,
"Bernex_za8",610L_za8,FR,4621.533N,00638.850E,880.0m,3,80,400.0m,,,"Page 196: 08/26 400m each. Grass or crops. Several parallel fields. Track divides area with step of 0.5m next to Track",,
"Bonneville_za8",615L_za8,FR,4604.283N,00621.900E,450.0m,3,0,300.0m,,,"Page 201: 450m Crops. Easy area. Likely cross wind as valley not aligned with field axis",,
"Bonnieux_za7",122L_za7,FR,4350.950N,00516.633E,180.0m,3,360,300.0m,,,"Page 94: Mainly N/S 300m Crops. Choose field",,
"Bourg d'Oisans_6",527M_6,FR,4504.217N,00601.967E,720.0m,3,340,350.0m,,,"Page 193: 34 only due to approach. Long Cables. Line up on hedge line down middle of field to fly over the cables. Land on right of the hedge.",,
"Caille_za8",226L_za8,FR,4346.883N,00644.167E,1080.0m,3,100,250.0m,,,"Page 122: 500m Crop. Choose field. Wet. (ULM Strip only 15m wide)",,
"CARPENTRAS_A",LFNH_A,FR,4401.683N,00505.033E,120.0m,4,130,850.0m,,"118.170","Page 5: Gliding. A/T. RW13/31. Circuit SW. Overhead join from NE. Use grass (with 300m hard)",,
"CERESTE_9",LF8421_9,FR,4351.167N,00532.950E,330.0m,2,80,800.0m,,"123.500","Page 12: 08/26 800m 123.50 Grass marked strip",,
"Chabottes_za7",315M_za7,FR,4439.000N,00611.333E,1080.0m,3,45,200.0m,,,"Page 140: Don't use the airstrip. Landing area to south of river.",,
"CHALANCON_A",LFJE_A,FR,4429.800N,00524.200E,890.0m,2,30,530.0m,,"130.000","Page 10: Altiport. Seriously uphill.",,
"CHALLES_A",LFLE_A,FR,4533.633N,00558.550E,299.0m,4,140,890.0m,,"118.400","Page 58: Gliding. A/T. Circuit NE. Probably use grass RW. Power circuit SW for hard RW.",,
"CHAMBERY_A",LFLB_A,FR,4538.350N,00552.800E,240.0m,5,180,2020.0m,,"118.300","Page 54: ATIS 127.100",,
"Chateauroux_6?",421D_6?,FR,4436.050N,00631.900E,860.0m,3,0,200.0m,,,"Page 170: Possible landing area. Pre walking essential. Power lines under construction.",,
"Coustellet_za8",121S_za8,FR,4351.683N,00510.800E,113.0m,3,90,350.0m,,,"Page 93: 09/27 350m ULM strip 20m wide. N of road with wind sock. Field S of road 11/29 better but could be high crops.",,
"Die_za7",511L_za7,FR,4446.050N,00521.333E,391.0m,3,50,300.0m,,,"Page 179: 300m Crops. Choose field. Beware power lines.",,
"Domaine de Malcor_7",316M_7,FR,4428.500N,00606.233E,620.0m,3,270,250.0m,,,"Page 141: Meadows",,
"Doussard_za8",620L_za8,FR,4546.817N,00613.033E,460.0m,3,0,300.0m,,,"Page 202: 300m Easy area Pasture & Crops. Choose field. Watch out for Hang-gliders/Paragliders",,
"Ecole-en-Bauges_7",623L_7,FR,4538.533N,00609.833E,731.0m,3,20,450.0m,,,"Page 206: 02/20 450m Hay. Near Road best to avoid lateral slope.",,
"ENVIE_9",ENV_9,FR,4441.733N,00724.150E,280.0m,5,170,630.0m,,"130.000","Page 42: 17/35 630m Grass. Towplane on airfield.",,
"Espinasses_8",317L_8,FR,4427.667N,00612.950E,650.0m,3,110,350.0m,,,"Page 142: 11/29 650m High Maise Crop after June. Land along rows.",,
"Eygalieres_7",112M_7,FR,4346.733N,00459.483E,100.0m,3,20,400.0m,,,"Page 88: SW/NE Grass/Stones Cables 1km SW. Only marked field, avoid other fields.",,
"EYGUIRES_A",LFNE_A,FR,4339.450N,00500.767E,75.0m,4,270,1280.0m,,"119.570","Page 8: Call Salon 135.150. Circuit to N of E/W runway, west of 33/15",,
"FAYENCE_A",LFMF_A,FR,4336.583N,00641.950E,227.0m,4,100,785.0m,,"119.050","Page 20: Gliding. RW10L/28R, Circuit N, & RW32 Circuit SW.",,
"Flayosc_ul8",232S_ul8,FR,4332.283N,00619.067E,365.0m,3,20,500.0m,,"123.500","Page 130: 20m wide. Private airfield. Located in restricted area R95 (freq 122.2). Sloped to north. LF8356",,
"GAP TALLARD_A",LFNA_A,FR,4427.183N,00602.167E,600.0m,4,30,700.0m,,"119.100","Page 26: Gliding. A/T. Parachuting W Side. Approach & Circuit always E side. Use smaller Runway E Side or Grass. ATIS 129.320",,
"Gordes_za7",120L_za7,FR,4354.633N,00514.900E,180.0m,3,360,300.0m,,,"Page 92: Mainly N/S 300m Crops. Choose field",,
"Grisail_7",522M_7,FR,4456.450N,00537.267E,807.0m,3,360,350.0m,,,"Page 186: 350m Pasture. Surface OK",,
"HABERE-POCHE_A",LF7469_A,FR,4616.250N,00627.783E,1113.0m,2,14,980.0m,,"122.500","Page 53: 02/20 980m Circuit E. PG's. Also possible landing at ULM field 320/2km (alt 600m)",,
"Isle Sorgue_za5",113Dza5,FR,4355.050N,00504.983E,65.0m,3,100,300.0m,,,"Page 90: Cultivated area. Several possible fields mainly NW/SE. Difficult landing.",,
"La Chapelle_6",227M_6,FR,4346.183N,00641.500E,1065.0m,3,90,350.0m,,,"Page 124: Landing possible in both directions. Possibility of pickets. If landing to W, do not land just after road - bad ground.",,
"La Faurie_6",310D_6,FR,4433.800N,00545.517E,820.0m,3,120,320.0m,,,"Page 134: 12/30 Low Crop. Cables. Recommend land SE",,
"LA MOTTE_A",LF0431_A,FR,4419.433N,00601.900E,650.0m,4,360,1170.0m,,"122.500","Page 32: 18/36 Gliding Winch. Circuit East. Slope. Normally land up to North, with offset final",,
"La Motte-en-Bauges_6",622M_6,FR,4542.617N,00607.017E,650.0m,3,160,600.0m,,,"Page 204: 15/33 600m Grass. Cable across field but can taxi under. Keep to centre to avoid low wall on E side near trees and post. If landing S, touch down after small wooden house near the road",,
"La Mure_7",222M_7,FR,4359.000N,00631.900E,930.0m,3,40,300.0m,,,"Page 116: 04/22 Grass. Land on shown area. Tree to SW limits 22 landing",,
"La Palud_za5",229D_za5,FR,4346.783N,00621.183E,890.0m,3,135,890.0m,,,"Page 126: Meadows. Inspection advised.",,
"La Roche_4",420DD_4,FR,4444.600N,00634.500E,940.0m,3,360,150.0m,,,"Page 169: Very difficult field. Pre walking essential - lots of ditches.",,
"Landry_5",721D_5,FR,4534.383N,00644.100E,750.0m,3,240,300.0m,,,"Page 218: Prefer land E. 250m Alfalfa. Paragliders. Prewalk essential. Circuit S. Other options in landout book.",,
"Laragne_ul8",313S_ul8,FR,4419.250N,00547.467E,570.0m,3,130,480.0m,,,"Page 138: 13/31 480m ULM strip. . Rough area next to river, not the nice looking field ending at the buildings. Circuit NE. Windsock both ends?",,
"Le Casset_8",411L_8,FR,4459.000N,00629.633E,1500.0m,3,110,500.0m,,,"Page 164: 10/28 Easy. Grass leisure area. Circuit S. Caution often walkers.",,
"LE MAZET_A",LFNZ_A,FR,4346.250N,00453.667E,100.0m,4,0,1000.0m,,"118.450","Page 7: Glider circuit to west.",,
"Le Rosier_5",413M_5,FR,4456.133N,00640.833E,1400.0m,3,360,400.0m,,,"Page 168: 18/36 400m Grass may be tall. Ditch across middle so land on second half. Windsock nr ditch. Buildings one end, middle of wood at the other.",,
"Les Crots_9",422S_9,FR,4432.183N,00626.083E,780.0m,3,60,450.0m,,"123.500","Page 172: 06up/24dn 450x40m Gravel. Nr Lake bed. Circuit N. LF0551",,
"Les Echelles_7",630L_7,FR,4525.817N,00545.833E,400.0m,3,0,300.0m,,,"Page 208: No specific difficulties. ~300m. Hay/Crops. Caution when hay is high. Small power lines.",,
"Logis du Pin_7",225L_7,FR,4346.367N,00638.017E,1025.0m,3,70,500.0m,,,"Page 120: 07/25 500m or 17/35 300m Grass. Walkers. Southern part often sodden",,
"Lourmarin_za7",126L_za7,FR,4345.233N,00524.117E,240.0m,3,20,400.0m,,,"Page 98: Cultivated area. N/S & E/W fields 400m. Choose field",,
"Luc en Diois_za8",513L_za8,FR,4435.500N,00528.383E,630.0m,3,150,300.0m,,,"Page 181: Landing zone. NW/SE 300m each. Crops. Another possible zone 3km SE.",,
"Mallemoisson_za7",325L_za7,FR,4401.800N,00605.000E,460.0m,3,0,300.0m,,,"Page 153: Landing area. Field according to crop.",,
"Mallemort",124L,FR,4344.700N,00510.500E,110.0m,3,300,500.0m,,,"Page 96: Meadows. Possibly cultivated. Field is near bridge between Merindol and Mallemort.",,
"Marcoux A_7",331AM_7,FR,4408.833N,00616.867E,700.0m,3,360,300.0m,,,"Page 156: N/S 300m Gravel. Next to river bed. Or local fields. Land on N half. E of river in forest",,
"Marcoux B_7",331BM_7,FR,4410.250N,00620.100E,800.0m,3,0,250.0m,,,"Page 156: Landing zone. Lots of small power lines.",,
"Marthod_5",720M_5,FR,4543.417N,00624.583E,380.0m,3,210,300.0m,,,"Page 216: Meadows. Pre walking essential.",,
"Megevette_5",611D_5,FR,4612.567N,00630.100E,900.0m,3,0,300.0m,,,"Page 197: Pre walking essential. Moveable fences. Meadows.",,
"Montgardin_6",318M_6,FR,4433.083N,00612.683E,800.0m,3,330,230.0m,,,"Page 144: RW33 up slope. 230m Bumpy ground. Marked threshold. Please don't use field to the south.",,
"Montmaur_7",311L_7,FR,4433.533N,00551.467E,900.0m,3,10,500.0m,,,"Page 136: ~500m Crops (marked field is N/S W of river) 2014-Stakes except within 40m of road.",,
"Montmeilleur_ul8",525S_ul8,FR,4447.600N,00545.800E,880.0m,3,85,550.0m,,"130.000","Page 190: Private airfield. Land towards the east (up slope). 20m wide from Google Earth.",,
"Montmelian_8",624L_8,FR,4529.700N,00602.000E,260.0m,3,150,400.0m,,,"Page 207: 15/33 400m grass. Windsock at N end. Sheep can be fenced in part of field in spring.",,
"Mousteiret_za7",224M_za7,FR,4347.917N,00638.100E,1080.0m,3,0,400.0m,,,"Page 119: Landing area. According to axis, you will have hills to fly along or over.",,
"Nossage_ul8",314S_ul8,FR,4418.750N,00544.700E,750.0m,3,20,550.0m,,"130.000","Page 139: 02/20 550m. Grass marked strip. Slope Up to SW. Threshold not at end of field. Circuit E.",,
"Noyers_6",321D_6,FR,4410.200N,00550.500E,560.0m,3,340,280.0m,,,"Page 148: Land 340 only.",,
"Orgon_7",114M_7,FR,4346.837N,00504.986E,90.0m,3,60,300.0m,,,"Page 91: 06/24 300m Grass/Crops. Avoid W end of field. NW of Pond. Land in either direction. Two choices of field - see landout book. San:2020:corrected coordinates and direction",,
"Oulx_5",410D_5,FR,4502.617N,00650.333E,1050.0m,3,270,250.0m,,,"Page 162: Meadows. Pre-walking essential.",,
"Passy_7",710L_7,FR,4555.100N,00643.167E,590.0m,3,160,600.0m,,,"Page 214: 16/34 600m Crops/Hay. Possible furrows between parcels. West part undulates less. HT cables N&S. Prefer land to S slighly downhill.",,
"Pellafol_za6",524M_za6,FR,4448.167N,00554.267E,940.0m,3,210,250.0m,,,"Page 189: 250m Crops. Area W of Vee lake and wind turbines. Choose field. SW is up slight slope. Cables NW/SE on Road to village.",,
"PIERRELATTE_A",LFHD_A,FR,4423.867N,00443.017E,60.0m,2,2,700.0m,,"118.970","Page 2: Gliders fly circuits to east.",,
"Prebois_za7",526M_za7,FR,4447.133N,00541.617E,760.0m,3,80,250.0m,,,"Page 192: 08 only. Slope up to east to village - land to east. Crops. Choose field probably W of village.",,
"Pruniere_8",423L_8,FR,4432.050N,00621.800E,860.0m,3,310,450.0m,,,"Page 174: Landing 310. Downwind on southern side. Meadows.",,
"Puget/Durance_8",125L_8,FR,4344.833N,00516.517E,133.0m,3,110,375.0m,,,"Page 97: 11/29 375m. Use marked area across middle of field (uncultivated). Can land across path across middle of field. 1.5m step at E end. Circuit N side. Land either direction, markers on north side.",,
"PUIMOISSON_A",LFTP_A,FR,4352.150N,00609.750E,777.0m,4,80,790.0m,,"123.500","Page 18: Gliding. A/T. 08/26 Circuit N & 16/34 Circuit W.",,
"Quinson_za7",210L_za7,FR,4341.217N,00604.083E,500.0m,3,360,500.0m,,,"Page 108: 500m slope Crop (up NW). Or choose other field. Two zones.",,
"Remoulins_ul",110S_ul,FR,4356.850N,00435.000E,25.0m,3,360,500.0m,,,"Page 86: 18/36 500x25m Grass ULM strip. Track OK to roll across. LF3025",,
"ROMANS ST PAUL_A",LFHE_A,FR,4503.867N,00506.067E,183.0m,4,60,885.0m,,"118.800","Page 44: Gliding A/T. 06R/24L & 02/20 circuit SE.",,
"Rosans_8",130L_8,FR,4422.917N,00528.300E,620.0m,3,360,400.0m,,,"Page 100: Slopes up to N. Crop. V turbulent in NW wind",,
"Rustrel_8",123L_8,FR,4355.100N,00528.000E,310.0m,3,270,400.0m,,,"Page 95: Crops. Land both directions.",,
"Saint-Blaise_5",412D_5,FR,4452.333N,00636.467E,1200.0m,3,50,300.0m,,,"Page 166: 05/23 300m Grass. 3xDitches. For 230 go under cables. Land exactly where road meets field. (very short if landing N with finals over trees)",,
"Salignac_za8",323L_za8,FR,4409.033N,00558.783E,518.0m,3,160,500.0m,,,"Page 151: 16/34 Landable zone. 500m Crops.",,
"SALLANCHES_A",LFHZ_A,FR,4557.000N,00638.333E,534.0m,5,350,600.0m,,"123.500","Page 64:",,
"Samoens_7",614L_7,FR,4604.167N,00644.417E,710.0m,3,160,500.0m,,,"Page 200: 16/34 500m Grass. Parcels of land marked by wooden pegs/stakes",,
"Saou_za7",510L_za7,FR,4438.083N,00503.633E,300.0m,3,110,400.0m,,,"Page 178: 400m Crops. Choose field.",,
"Sederon_6",131M_6,FR,4413.250N,00534.617E,750.0m,3,90,300.0m,,,"Page 102: E/W Landing zone 300m Crop. Cables & 3 Poplars at E end so land E if calm. Or land diagonally NW. Caution turbulence in NW winds. Other field options in landout book.",,
"Selonnet A_za7",SelA_za7,FR,4422.100N,00618.600E,1100.0m,3,0,250.0m,,,"Page 154: Possible landing area",,
"Selonnet B_za7",SelB_za7,FR,4420.800N,00619.900E,1150.0m,3,0,250.0m,,,"Page 154: Possible landing zone",,
"SERRES_A",LFTM_A,FR,4427.383N,00543.633E,705.0m,4,360,650.0m,,"123.500","Page 24: Gliding A/T. RH Circuit.",,
"SEYNE_A",LF0430_A,FR,4420.583N,00622.267E,1200.0m,4,130,900.0m,,"118.450","Page 36: 13/31 900m Gliding. Grass Strip. Slight Step in middle. Circuit SW. Land Parcours side as smoother.",,
"SION_A",LSGS_A,FR,4613.167N,00719.600E,483.0m,5,70,2000.0m,,"126.825","Page 62. App-126.825 Twr 118.275",,
"SISTERON_A",LFNS_A,FR,4417.200N,00555.750E,540.0m,4,360,1160.0m,,"120.050","Page 30: Gliding A/T. Circuit East. Use Grass RW & Taxi West",,
"Soleihas_6",223D_6,FR,4351.217N,00638.817E,1120.0m,3,300,250.0m,,,"Page 118: Field sloped, land NW only. Road at entry to field is 50cm higher than field.",,
"SOLLIERRES_A",LFKD_A,FR,4515.233N,00648.067E,1309.0m,4,20,620.0m,,"123.500","Page 68:",,
"St Jalle_za5",132D_za5,FR,4420.117N,00518.033E,440.0m,3,120,250.0m,,,"Page 104: 12/30 440m Crops. Choose field. Cables SW. Circuit NE (land under cables??)",,
"St Jeoire_5",612D_5,FR,4608.600N,00628.200E,590.0m,3,0,250.0m,,,"Page 198: Pre walking essential. Land towards the north.",,
"St Laurent_6",631L_6,FR,4524.017N,00543.850E,400.0m,3,0,350.0m,,,"Page 209: Small power lines. Pasture. Choose field. Caution when crops high.",,
"St Vincent de Mercuz_ul8",632L_ul8,FR,4522.267N,00558.200E,260.0m,3,20,300.0m,,,"Page 210: 02/20 300m 2x fields slope towards each other. Approach over one and land in second. Trees and power line at NE end of field 2.",,
"StAUBAN_A",LFMX_A,FR,4403.500N,00559.450E,463.0m,4,20,1200.0m,,"122.300","Page 34: Gliding A/T & Winch. 02/20 circuit NW",,
"StCREPIN_A",LFNC_A,FR,4442.033N,00635.950E,903.0m,4,160,780.0m,,"123.500","Page 38: Gliding A/T & Winch?. 16L/34R Circuit NE. Grass runway to east of hard.",,
"StCROIX_A",LF0429_A,FR,4346.733N,00609.567E,655.0m,2,130,700.0m,,"123.500","Page 16: 13/31 700m Motor Glider strip. Masts & cables to NW",,
"StJEAN_A",LFKE_A,FR,4501.583N,00518.550E,264.0m,2,320,667.0m,,"123.500","Page 46: St Jean en Royans.",,
"St-Jean d'Herans_za6",523Lza6,FR,4451.317N,00546.200E,825.0m,3,80,300.0m,,,"Page 188: 300m Cables vis. Slight slope up to E/W road. Fields slope gently down in northern and southern areas.",,
"StREMY_A",LFKR_A,FR,4522.633N,00616.583E,426.0m,5,160,757.0m,,"123.500","Page 70: Strong valley winds. Normally RW34. Retrieve possible. See VFR Plate.",,
"Taninges_za7",613Lza7,FR,4605.833N,00637.867E,625.0m,3,90,300.0m,,,"Page 199: 09/27 300m Grass. Mown into strips. Movable fences possible",,
"Tarascon_ul9",111S_ul9,FR,4346.817N,00441.400E,8.0m,3,10,400.0m,,,"Page 87: 01/19 400m Grass ULM strip E of sock. Taxiway W of sock landable. LF1351",,
"Thorame basse_6",221M_6,FR,4404.600N,00628.433E,1100.0m,3,310,300.0m,,,"Page 114: RW31 only up slope. 300m keep R. Bank at start. Ditch at end. Circuit NE. V turbulent in NW wind.",,
"Thorame haute_5",220DD_5,FR,4405.717N,00633.617E,1100.0m,3,310,250.0m,,,"Page 113: Difficult field. Sloped. Land towards NW. Left hand circuit; base leg along mountain. Turbulence and rotors in NW winds.",,
"Thouard_za6",324D_za6,FR,4407.050N,00607.700E,670.0m,3,0,250.0m,,,"Page 152: Landing area. Choose field according to crops.",,
"Trets_ul",214S_ul,FR,4328.783N,00542.650E,240.0m,3,120,400.0m,,"123.450","Page 112: 12/30 400m ULM strip. 27m wide. Marked strip.",,
"Trigance_6",228M_6,FR,4345.250N,00627.350E,740.0m,3,130,300.0m,,,"Page 125: 13/31 400m Grass. Prewalking advised.",,
"VALENCE CHABEUIL_A",LFLU_A,FR,4454.933N,00458.117E,162.0m,5,10,1190.0m,,"120.100","Page 48:",,
"Valenty_7",312M_7,FR,4421.600N,00555.783E,570.0m,3,210,400.0m,,,"Page 137: 21 up slope. 400m. Edge of Plateau. E/W Cable at end no problem. Risk of turbulence on short final.",,
"VALREAS_A",LFNV_A,FR,4420.150N,00454.417E,140.0m,2,20,1020.0m,,"123.500","Page 4: Valreas Visan. LFNV",,
"VERSOUD_A",LFLG_A,FR,4513.083N,00550.900E,222.0m,4,40,900.0m,,"121.000","Page 60: Gliding. A/T. Circuit NW. Use Grass RW.",,
"Vif_za8",520L_za8,FR,4504.450N,00540.600E,288.0m,3,20,350.0m,,,"Page 182: Hay/Crops, Easy area. Beware of cable crossing area.",,
"VINON_A",LFNF_A,FR,4344.350N,00547.017E,277.0m,4,100,1260.0m,,"118.150","Page 14: Gliding. Runways everywhere. See VFR Plate.",,
"Vizille_6",521M_6,FR,4504.850N,00546.700E,280.0m,3,30,350.0m,,,"Page 184: 03 350m Crop",,
"Volonne_za7",322L_za7,FR,4406.100N,00600.000E,490.0m,3,360,250.0m,,,"Page 150: Landing area. Choose fields according to crops",,
"Voreppe_za7",633L_za7,FR,4516.217N,00537.933E,200.0m,3,0,400.0m,,,"Page 211: Choose field. Caution crop and power lines.",,
"CAMPITELLO_FASSA_7",CAMPIT_7,IT,4628.047N,01143.658E,1383.0m,3,250,280.0m,,,"DIREZIONE MIGLIORE SW ATTERRARE DOPO LA STRADINA. CVNE AGGIUNTO IO  s:ENE20",,
"Armentarola_5",Arment_5,IT,4633.209N,01158.010E,1653.0m,3,170,200.0m,,,"SOLO verso S leggera salita. Alberi alti in testata S, stradina ATTEMZIONE CNVE  s:ENE20",,
"Laggio_5",Laggi5,IT,4630.083N,01228.717E,900.0m,3,180,180.0m,,,"Sehr kurz! Landing towrds S (180°). W45. Kat 2Checked A144 CVNE  s:ENE20",,
"AVIANOST_7",AVST7,IT,4604.928N,01234.862E,200.0m,3,240,350.0m,,"120.965","Meglio verso SudOvest Avianostella Nuovo Contattare Aviano 120.965 Fonte CVNE  s:ENE21 pictures:AVS",,"N092E012_AVIANO_STELLA.jpg;N092E012_AVIANO_STELLA_SK.jpg"
"AGORDO_7",AGORD7,IT,4616.783N,01201.783E,600.0m,3,160,400.0m,,,"Recomended landing direction 160, tra eliporto e fiume, paletti a meta' pista°. A06+W57. Kat 1 CVNE  s:ENE20 pictures:AVS",,"N092E012_AGORDO_SK.jpg;N092E012_img557.jpg;N092E012_img560.jpg"
"Pieve_5",Pieve5,IT,4626.883N,01223.783E,740.0m,3,270,150.0m,,,"Sehr kurz! Land towards 270°. W46. Kat 2 Pieve di Cadore A212-CVNE  s:ENE20",,
"Coccau_4",Coccau_4,IT,4631.000N,01336.533E,773.0m,3,310,190.0m,,,"campo corto ma in salita in erba ATTERRARE corti SOLO VERSO nord-ovest. utilizzare la parte destra del campo regolare CVNE  s:ENE20",,
"FORNOdiZOLDO_7",FORNZD_7,IT,4620.898N,01211.180E,865.0m,3,300,220.0m,,,"dir solo NW - vicino piazzola Elicotteri - occhio al traffico - mantenendosi paralleli alla strada sulla parte destra del campo CVNE  s:ENE20",,"N000W001_FORNO_DI_ZOLDO_SK.jpg;N000W001_FORNO_DI_ZOLDO_1.png"
"Malborghetto_4",Malbo_4,IT,4630.333N,01325.767E,720.0m,3,80,200.0m,,,"Direzione obbligatoria verso EST, larghezza 45, piccola recinzione bassa all'inizio, imperativo toccare il prima possibile. La lunghezza limitata a 200 a causa del pericoloso canale di scolo a 3/4 della lunghezza totale del campo. Malborghetto CVNE.  s:ENE20",,
"DARDAGO_N_6",DARDn6,IT,4603.433N,01232.710E,170.0m,3,270,300.0m,,"122.100","Larghezza 40 m, direzione obbligatoria 270, scalino a 3/4 di pista da evitare. Dentro l'ATZ di Aviano , contattare 120.12, adiacente zona atterraggio delta e para. Fare sottovento a sud. Preferire il campo di DARDAGO SUD, se possibile CVNE  s:ENE20",,"N092E012_DARDAGO_NORD.jpg"
"DARDAGO_S_7",DARDs7,IT,4603.002N,01232.641E,165.0m,3,90,250.0m,,"122.100","Larghezza 40/50 mt verso su ovest, ampia ma con degli alberi entrando verso nord est. dentro l'ATZ di Aviano, meglio contattare prima AVIANO 120.12. CVNE  s:ENE20",,"N092E012_DARDAGO_SUD_SK.jpg;N092E012_DARDAGO_SUD.jpg;N092E012_DARDAGO_SUD_NORD.jpg"
"Sappada_4",Sappada4,IT,4634.000N,01241.600E,1230.0m,3,70,170.0m,,,"ATTERRARE ALL'ALTEZZA DEL PONTICELLO VERSO EST (BANDIERE). TENERE IL PONTICELLO A SX. leggera salita area W del ponticello non utilizzabile per paletti CVNE  s:ENE20",,"N093E012_sappada_1.jpg;N093E012_sappada_2.jpg;N093E012_sappada_3.jpg"
"VVISDENDE_7",VVISDE7,IT,4637.089N,01237.885E,1280.0m,3,290,300.0m,,,"Val Visdende 290 OBBLIGATORIO - USARE PARTE EST CNVE - secondo loro buono  s:ENE20",,
"LONGARONE_7",LONGA7,IT,4616.583N,01218.250E,470.0m,3,175,400.0m,,,"MOLTO SCONNESSO A NORD DELLA MANICA A VENTO - ATTERRARE PER S-O EVITANDO I PRIMI METRI SCONNESSI - POSSIBILI FIERE - ATTENZIONE PALETTI NELLA PARTE SUD VICINO AL PARCHEGGIO FIERA CVNE  s:ENE20",,"N092E012_longarone_1.jpg;N092E012_longarone_2.jpg"
"PADOLAVAL_8",PADVAL_8,IT,4637.859N,01226.922E,1300.0m,3,270,500.0m,,,"Atterrare verso Ovest Nuovo Campo fonte:CVNE. Padola Valgrande  s:ENE20",,
"CERCIVENTO_ul9",CERC_ul9,IT,4631.435N,01300.239E,555.0m,5,45,350.0m,,,"SALITA VERSO NE UL field fonte:CVNE non su avioportolano  s:ENE20",,
"Cavazzo Carnico_5",Cavaz_5,IT,4622.667N,01302.517E,294.0m,3,340,170.0m,,,"SCONSIGLIATO MEGLIO CAVAZZO BASSO O CAVAZZO ALTO  atterrare per 34/16 nel campo a fianco del frutteto possibili coltivazioni terreno abbastanza sconnesso campo corto ATTENZIONE paletto metano in testata S e altro in testata N. CVNE  s:ENE20",,"N092E013_cavazzo_1.jpg;N092E013_cavazzo_2.jpg"
"CAVAZZO ALTO_7",CAVALT_7,IT,4621.433N,01302.283E,373.0m,3,300,400.0m,,,"BUONO entrata DA EST paralleli alla linea di alta tensione - puntare su 2 alberelli a inizio  campo - campo in leggera salita molto regolare - preferibile a cavazzo basso  s:ENE20",,"N092E013_cavazzoalto_1.jpg;N092E013_cavazzoalto_2.jpg;N092E013_cavazzoalto_3.jpg"
"CAVAZZO BASSO_6",CAVBAS_6,IT,4622.083N,01301.900E,297.0m,3,270,200.0m,,,"DISCRETO: dal paese puntare sul cespuglio dopo la strada atterrare CORTI verso OVEST - attenzione fossato a 3/4 di pista CVNE  s:ENE20",,"N092E013_cavazzo_basso_1.jpg;N092E013_cavazzo_basso_2.jpg"
"CARNIA_NORD_8",CARN_N8,IT,4622.133N,01307.783E,260.0m,3,180,350.0m,,,"LUNGHEZZA 350M. ATTENZIONE POSSIBILI COLTIVAZIONI, BUONO E  PREFERIBILE (SE NON COLTIVATO) A CARNIA SUD. ATTENZIONE A META' CAMPO AVVALLAMENTO ATTERRARE PREFERIBILMENTE DIREZIONE SUD. CVNE  s:ENE20",,"N092E013_carnia_1.jpg;N092E013_carnia_2.jpg"
"CARNIA_SUD_6",CARNI_s6,IT,4621.700N,01307.933E,250.0m,3,0,200.0m,,,"PREFERIBILE IN DIREZIONE NORD ENTRATA SENZA OSTACOLI ATTERRARE CORTI PRIMA DELL'ALBERELLO. SE IN DIREZIONE S ATTENZIONE ALL'ENTRATA: LINEA ELETTRICA A E E ALBERELLO: E' NECESSARIO ENTRARE BASSI TRA ALBERELLO E LINEA ELETTRICA (40 MT) CVNE  s:ENE20",,"N092E013_carnia_1000.jpg;N092E013_carnia_2000.jpg"
"CIMOLAIS_ul9",CIMO_UL9,IT,4615.883N,01228.067E,565.0m,3,350,250.0m,,,"AVIOSUPERFICIE: ATTERRARE SOLO PER 35 CAMPO IN SALITA AL 6% VERSO NORD. CVNE  s:ENE20",,"N092E012_cimolais_1.jpg;N092E012_cimolais_2.jpg;N092E012_cimolais_3.jpg"
"CORTINA_CAM_6",CORca6,IT,4631.200N,01208.000E,1150.0m,3,0,300.0m,,,"SOLO CON VENTO DA NORD. DISCRETO: dir. 0/- CAMPO IN SALITA usare solo la parte sud  prima della stradina. finale sopra il campeggio altri campi in forte salita piu' a nord con brezza da sud usare aeroporto. visto 2019 leo-paolo CVNE  s:ENE20",,"IMGB195.jpg;IMGDD38.jpg"
"SOVERZENE_6",SOVERZ_6,IT,4612.967N,01217.817E,408.0m,3,180,180.0m,,,"in leggera discesa attacco a 0 dopo toccare corti campo corto usato da aeromodellisti cinesini e manica a vento - alternativa se longarone non disponibile. CVNE  s:ENE20",,"N092E012_soverzene_1.jpg;N092E012_soverzene_2.jpg"
"SMartino_Badia_5",SMBadi_5,IT,4640.683N,01153.567E,1200.0m,3,270,450.0m,,,"in salita attacco a 0 sopra strada atterrare solo verso OVEST paralleli alla linea telefonica - campo lungo e regolare. visto 2019 leo-paolo. CVNE  s:ENE20",,"N093E011_sanmartino1.jpg;N093E011_sanmartino2.jpg;N093E011_sanmartino3.jpg"
"CORVARA_8",CORVA_8,IT,4633.150N,01151.833E,1550.0m,3,270,300.0m,,,"BUONO: 27/- atterrare SOLO verso Ovest in leggera salita - nel 2015 presenti cinesini delimitatori di testa pista ovest . Occhio alla  visto 2019 leo-paolo CVNE  s:ENE20",,"N093E011_corvara_1.jpg;N093E011_corvara_2.jpg;IMG7C16.jpg"
"Tramonti_4",Tramon_4,IT,4617.117N,01248.133E,372.0m,3,350,170.0m,,,"CORTO!: STRADA A INIZIO DEL CAMPO attacco a 0 atterrare verso nord toccare almeno 10 mt dopo strada (fossato) - possibile anche atterraggio da Ovest a est paralleli a strada. Tramonti di Sotto CVNE  s:ENE20",,"N092E012_tramonti_1.jpg;N092E012_tramonti_2.jpg"
"MANIAGO_UL9",MANI_UL9,IT,4607.500N,01243.833E,250.0m,3,170,1200.0m,,,"OTTIMO: AVIOSUPERFICIE ENORME. CONSIGLIATO ATTERRAGGIO PARALLELO ALLA STRADA VICINO LA MANICA A VENTOCVNE   s:ENE20",,"N092E012_maniago_1.jpg;IMGAF78.jpg"
"OBERVINTL_7",OBERVI_7,IT,4648.683N,01145.017E,750.0m,3,100,400.0m,,,"Medio 10/28 CON ALTERNATIVE attenzione parzialmente coltivato con fossato divisorio vari campi verificare possibili coltivazioni. visto 2019 leo-paolo. Vandoies Obervintl CVNE  s:ENE20",,"N093E011_obervintl_1.jpg;N093E011_obervintl_2.jpg"
"KOBARID_8",KOBAR_8,SI,4614.783N,01332.450E,251.0m,3,80,300.0m,,,"BUONO. DIR 08/26 CAMPO PARALLELO ALLA STRADA FOSSO IN TESTATA 08 TERRENO CON DIFFICOLTA' DI DRENAGGIO ultima visita 2017. CVNE  s:ENE20",,"N092E013_kobarid_2.jpg;N092E013_kobarid_1.jpg;N092E013_kobarid_3.jpg;N092E013_kobarid_4.jpg"
"GODZ2_7",GODZ2_7,SI,4628.919N,01351.103E,732.0m,3,90,250.0m,,,"BUONO SOLO EST CVNE SCHEDA  s:ENE20 pictures:AVS",,"N092E013_0050.jpg;N092E013_img503.jpg;N092E013_img506.jpg"
"GODZ1_7",GODZ1_7,SI,4628.796N,01351.490E,730.0m,3,270,220.0m,,,"BUONO. 220 metri ATTERRARE PER 27 DOPO LA RECINZIONE CHE TAGLIA IL CAMPO. alternative piu' a ovest vedi foto ultima visita 2017 GodzMartulje modificato coordinate CVNE  s:ENE20",,"N092E013_gozd_1.jpg;N092E013_gozd_2.jpg;N092E013_gozd_3.jpg"
"Vipiteno_9",VIPIT_9,IT,4653.017N,01126.617E,939.0m,5,130,550.0m,,"122.600","Military, gliders, grass field  s:ENE20",,
"FEDERAUN_6",FEDERA,AT,4634.233N,01347.967E,509.0m,3,260,500.0m,,,"MEDIO 26  Solo in caso di impossibilita' a raggiungere Noetsh - Campi coltivati SIP 0186_s:ENE20",,"N093E013_federaun_1.jpg;N093E013_federaun_2.jpg"
"LENDORF_8",LENDOR_8,AT,4649.917N,01325.017E,600.0m,3,100,900.0m,,,"FACILE 250 metri. vicino al laghetto. atterrare per 10/28. strada in mezzo al campo facilmente evitabile in sicurezza. Ultima visita:2017. CVNE COORDINATE MODIFICATE  s:ENE20",,"N093E013_lendorf_3.jpg;N093E013_lendorf2.jpeg;N093E013_lendorf1.jpeg"
"Malta_5",Malta_5,AT,4658.600N,01328.133E,830.0m,3,160,530.0m,,,"BUONO 16/34 - ALTA TENSIONE parallela sul lato ovest del prato sul lato est recinzione SIP 0513_s:ENE20",,"N093E013_malta_3.jpg;N093E013_malta_1.jpg;N093E013_malta_2.jpg"
"PATERNION_8",PATERN_8,AT,4643.152N,01338.341E,510.0m,3,120,300.0m,,,"FACILE 350 metri  atterrare per 12/30. In zona disponibili molti altri campi alternativi. CVNE COORDINATE MODIFICATE  s:ENE20",,"N093E013_paternon_4.jpg;N093E013_paternon_1.jpg;N093E013_paternon_2.jpg;N093E013_paternon_3.jpg"
"KRANSKAGORA_7",KRANSK_7,SI,4629.276N,01346.927E,830.0m,3,90,300.0m,,,"Attenzione a LINEE ELETTRICHE paletti ostacoli fossati e recinzioni - per 09  campo lato SUD - paese - paralleli alla linea elettrica - campo un po stretto - manica a vento  preferibile RATECE ultima visita 2017. CVNE. COORDINATE MODIFICATE  s:ENE20",,"N092E013_kranskagora_1.jpg;N092E013_kranskagora_2.jpg;N092E013_kranskagora_4.jpg"
"RATECE_7",RATEC2_7,SI,4629.402N,01343.346E,870.0m,3,180,300.0m,,,"Buono: 300 metri in salita 3-4% atterrare solo per 190 ingresso a 0: qualche ondulazione da EVITARE.  ultima visita 2017. CVNE COORDINATE MODIFICATE  s:ENE20",,"N092E013_ratece.jpg;N092E013_ratece2.jpg;N092E013_ratece3.jpg"
"TOLMIN-OVEST_6",TOLOVE_6,SI,4611.050N,01343.167E,157.0m,3,150,290.0m,,,"PREFERIRE VOLARJE. ATTENZIONE POSSIBILI PALETTI DI RECINZIONE MOBILI! - ATTERRABILE SOLO PER 150 CON ATTACCO QUASI A 0 ultima visita 2017. CVNE. Eventuale emergenza a N con In alternativa si piò atterrare - esclusivamente in direzione Nord! - sul campo para, avendo l'attenzione di NON atterrare corti, visto che la prima parte del campo è fortemente ondulata e ha anche un canale di scolo pericoloso. Dalla metà in poi ci sono almeno 250 metri utilizzabili.  s:ENE20",,"N092E013_tolmin_2.jpg;N092E013_tolmin_1.jpg"
"VOLARJE_7",VOLARJ_7,SI,4612.283N,01340.517E,174.0m,3,270,330.0m,,,"BUONO: ATT PER 27/-TRA LA STATALE E IL FIUME - LEGGERE ONDULAZIONI NELLA PARTE NORD OVEST - ATTERRARE VERSO NO - LEGGERA SALITA - ENTRATA A 0 TRA LA STRADA E UN RUDERE PALETTI BASSI IN TESTATA ultima visita 2017. CVNE  s:ENE20",,"N092E013_volarje2.jpg;N092E013_volarje1.jpg;N092E013_volarie3.jpg;N092E013_volarie4.jpg"
"Feffernitz_7",FEFFE2_7,AT,4641.550N,01341.733E,506.0m,3,40,350.0m,,,"MEDIO atterrare per 04. non superare la linea elettrica rullando perche' c'e' un FOSSO!  SIP 0367_s:ENE20",,"N093E013_feffernitz_1.jpg;N093E013_feffernitz_2.jpg"
"Feldkirchen_AE",LOKF,AT,4642.517N,01404.617E,520.0m,2,200,700.0m,,"122.705","Att frequenza 8.33 per 20/200 sottovento alianti a E s:ENE20",,"IMG85AB.jpg;IMGDA9F.jpg"
"Glanz_8",GLANZ2_8,AT,4644.433N,01302.933E,608.0m,3,270,400.0m,,,"FACILE: 400 metri atterrare per 28 s:ENE20",,
"Hermagor_8",HERMA2_8,AT,4637.700N,01323.150E,595.0m,3,90,600.0m,,,"MEDIO 800 metri atterrare per 09/27 linee alta tensione su testata 09 Preferibile Modendorf a 3 km: - fosso in mezzo al prato - nuova recinzione sul lato ovest! s:ENE20",,"N093E013_hermagor_2.jpg;N093E013_hermagor_1.jpg;N093E013_hermagor_3.jpg"
"LEISACH_7",LEISAC_7,AT,4648.417N,01244.933E,670.0m,3,210,300.0m,,,"Medio - att. per 21 - 2 campi disponibili tra il paese e il fiume - linea elettrica parallela ai campi - uno a sud del paese a fianco della statale l'altro a est dell'abitato SIP 0207_s:ENE20",,"N093E012_leisach_1.jpg;N093E012_leisach_2.jpg;N093E012_leisach_3.jpg"
"Lienz-Nickolsdorf_AE",lokn_AE,AT,4647.880N,01252.703E,636.0m,5,120,620.0m,,"122.505","dir 12/22 sottovento alianti a est attenzione raffiche e turbolenze severe con temporali. Coordinate modificate s:ENE20",,
"MATREI-OSTTIROL_8",MATREI_8,AT,4659.117N,01232.767E,925.0m,3,150,250.0m,,,"FACILE 15/-  atterrabile in entrambi i sensi nel campo a ovest dello stadio. fossati ai lati e a fine campo - manica a vento campo aeromodelli -  linee di alta tensione parallele alla pista da entrambi i lati s:ENE20",,"N093E012_matrei_1.jpg;N093E012_matrei_2.jpg"
"Mauthen_ZA7",Mauthe_7,AT,4639.750N,01301.800E,680.0m,3,290,300.0m,,,"BUONO:  300 metri ATTERRARE preferibilmente per 29 - vari campi disponibili  leggerissima salita verso ovest. Uno e' un campo aeromodelli e manica a vento  s:ENE20",,"N093E013_mauten_2.jpg;N093E013_mauten_3.jpg;N093E013_mauten.jpg"
"MOEDERNDORF_8",MOEDER_8,AT,4636.700N,01321.233E,580.0m,3,290,400.0m,,,"FACILE -/29 subito a sud del fiume - 2 possibilita' a sud o nord della stradina che taglia il campo - linea elettrica  trasversale a meta' campo - meglio di hermagor!  s:ENE20",,"N093E013_moederndorf_1.jpg;N093E013_moederndorf_2.jpg;N093E013_moederndorf_3.jpg"
"Notsch_AE",LOKN_AE,AT,4634.833N,01337.700E,549.0m,2,90,710.0m,,"122.405","DIR 09/27 sottovento alianti a Nord LINEA ELETTRICA A SUD DEL CAMPO attenzione frequenza cambiata 2018 s:ENE20",,"IMGB725.jpg"
"Obertilliach_7?",Ober_7?,AT,4642.067N,01238.067E,1367.0m,3,280,300.0m,,,"MEDIO: solo PER 28/- A EST DI OBERTILLIACH. IL CAMPO SALE VERSO OVEST, LINEA ELETTRICA A NORD DEL CAMPO possibile alternativa a sud est del paese SU campo in salita VEDI FOTO. SAN: CHECK COORDINATES s:ENE20",,"N093E012_obertilliach_1.jpg;N093E012_obertilliach_2.jpg;N093E012_obertilliach_3.jpg"
"Rattendorf_jenig_5",RATTE2_5,AT,4637.450N,01314.283E,600.0m,3,130,600.0m,,,"600 metri atterrare per 13/31 diversi fossati linea el a sud del campo meglio Tressdorf a 3 km di distanza: SEGNALATO COME DIFFICILE ROSSO s:ENE20",,"N093E013_rattendorf_1.jpg;N093E013_rattendorf_2.jpg;N093E013_rattendorf_3.jpg"
"Seeboden_6",SEEBO2_6,AT,4649.500N,01330.267E,657.0m,3,150,320.0m,,,"MEDIO 320 metri - atterrare per 14/32: pratiche agricole presenti! SIP_0344_s:ENE20",,"N093E013_seeboden_1.jpg;N093E013_seeboden_2.jpg;N093E013_seeboden_3.jpg"
"Sillian-new_7",Sillia_7,AT,4644.883N,01225.833E,1103.0m,3,90,400.0m,,,"BUONO. ATTERRABILE PER 08 O 26 PARALLELI AL FIUME. EVITARE I PRIMI 50 METRI LATO EST C'e' UN CANALE. MANICA A VENTO ATTERRAGGIO PARA LATO NORD. ALTRI CAMPI piu' A EST s:ENE20",,"N093E012_sillian.jpg"
"Steinfeld_Gerlamoos_8",GERLA2_8,AT,4645.617N,01317.050E,574.0m,3,90,500.0m,,,"BUONO: 500 metri atterrare per 09/27  s:ENE20",,"IMG58D.jpg"
"TREFFEN_8",TREFFE_8,AT,4639.600N,01352.000E,515.0m,3,140,500.0m,,,"FACILE 14/32  a nord est della statale - campo di dimensioni imperiali ultima visita 2017 s:ENE20",,"N093E013_treffen_3.jpg;N093E013_treffen_4.jpg"
"TRESSDORF_8",TRESSD_8,AT,4638.150N,01312.050E,610.0m,3,110,300.0m,,,"FACILE 11/29 - a nord della strada a centro valle - diverse opzioni ATTENZIONE albero al centro CVAO CV_182_s:ENE20",,"N093E013_tressdorf_1.jpg;N093E013_tressdorf_2.jpg;N093E013_tressdorf_3.jpg"
"Uggovitz_8",Uggovi_8,AT,4640.417N,01344.250E,505.0m,3,110,450.0m,60.0m,,"FACILE E SICURO in entrambe le direzioni. linee elettriche parallele a S-W. Atterrato nel 2019 s:ENE20",,
"Vorderberg_8",VORNO_8,AT,4635.517N,01330.917E,570.0m,3,120,400.0m,,,"400 metri atterrare per 12: SEGNALATO COME facile VERDE con foto  da outlanding guide Austria_AT s:ENE20",,
"Belluno_AE",BELLU_AE,IT,4609.936N,01214.935E,378.0m,2,50,800.0m,,"119.650","atterrare per 05/23 SOTTOVENTO A SUD SOPRA IL PIAVE s:ENE20 ",,"IMG3C76.jpg;IMG7DCB.jpg"
"Brunico_7",Bruni_7,IT,4648.700N,01155.633E,835.0m,3,360,400.0m,,,"CAMPO IN LEGGERA SALITA VERSO NORD  s:ENE20",,"IMG25CD.jpg;IMG7767.jpg"
"CAMPO TURES_8??",TAUFE_8?,IT,4654.817N,01157.533E,870.0m,3,160,450.0m,,,"Facile 16/34 atterraggio ULM - larghezza 20m manica a vento in testata 34 tra la zona industriale e il paese di campo tures SIP 0477_s:ENE20",,"N093E011_TAUFERS_1.jpg;N093E011_TAUFERS_2.jpg;N093E011_TAUFERS_3.jpg"
"Dobbiaco_AE",LIVD,IT,4643.600N,01213.817E,1240.0m,2,100,800.0m,,"118.850","dir. 10/28 AEROPORTo MILITARE CONTROLLO DOCUMENTI attenzione traino vietato ai non soci s:ENE20",,
"ENEMONZO",ENEMONZO,IT,4624.250N,01253.100E,376.0m,2,80,450.0m,,"122.000","ATT 08/26 SOTTOVENTO ALIANTI A NORD DEL CAMPO DOSSO IN TESTATA 08 s:ENE20",,"N092E012_enemonzo_3.jpg;N092E012_enemonzo_4.jpg"
"Gagliano_9",GAGLIA_9,IT,4603.406N,01325.577E,100.0m,4,0,400.0m,,,"alberi in testata 18. SAN: coordinate modificate s:ENE20",,"IMG4C2.jpg"
"Gorizia_AE",GORIZ_AE,IT,4554.367N,01335.967E,60.0m,2,40,750.0m,,"119.850","Pista chiusa al traffico s:ENE20",,"IMG8342.jpg;IMGE437.jpg"
"GSIESSERTAL ULM9",GSIESS_9,IT,4645.933N,01209.667E,1200.0m,3,80,400.0m,,,"Facile  ULM - 08/26 a sud della statale sul fianco sud del lungo filare di alberi ben visibile a centro valle - stradina taglia a meta' atterrato Sandro Taddio SIP 0376_s:ENE20",,"N093E012_gsiessertal_1.jpg;N093E012_gsiessertal_2.jpg;N093E012_gsiessertal_3.jpg"
"Mantana_6?",Manta_6?,IT,4646.467N,01152.117E,826.0m,3,45,200.0m,,,"dir 45/- leggera salita parzialmente coltivato. visto 2019 leo-paolo s:ENE20",,
"OLANG-VALDAORA_7",OLANGA_7,IT,4645.350N,01201.467E,1095.0m,3,180,300.0m,,,"Facile 18/- parallelo a stradina - a sud ovest di Valdaora di Sopra SIP 0143_s:ENE20",,"N093E012_olang_valdaora_1.jpg;N093E012_olang_valdaora_2.jpg;N093E012_olang_valdaora_3.jpg"
"Paluzza_6?",PALUZ_6?,IT,4632.950N,01300.783E,690.0m,3,350,300.0m,,,"ATTERRARE VERSO NORD PENDENZA DEL 4% A SALIRE VERSO NORD. PREFERIRE campo ULM di Cercivento s:ENE20",,
"Primulacco_7",PRIMUL_7,IT,4608.000N,01316.700E,130.0m,4,350,310.0m,,,"dir 35/- SOLO PER ALIANTI DI 15m. Circuito sempre ad EST del campo. Linee elettriche h 13 m a circa 300 mt da entrambe le testate.  s:ENE20",,"IMG10D7.jpg;IMG4917.jpg"
"Rivoli di Osoppo_AE",Rivol_AE,IT,4614.150N,01304.400E,170.0m,2,30,650.0m,,"123.000","SOTTOVENTO SX PER PISTA 03 s:ENE20",,
"San Mauro_9",SMAURO_9,IT,4604.102N,01322.148E,110.0m,2,90,500.0m,,"121.900","ALIANTI ATTERRARE PER 27 linea elettrica in testata 27. SAN:CambioCoord s:ENE20",,"IMGBF2C.jpg;IMGEEC5.jpg;IMG4426.jpg"
"SESTO_6",SESTO_6,IT,4641.633N,01221.533E,1325.0m,3,135,450.0m,,,"dir pref. 13/-  IN LEGGERA SALITA PER 13 . arrivare LUNGHI. PALETTI e avvallamenti a meta' campo MANICA A VENTO s:ENE20",,
"VERSCIACO_6?",VIERS_6?,IT,4643.683N,01219.500E,1150.0m,3,90,450.0m,,,"Medio - 09/27 a sud della statale linea elettrica parallela a fianco della statale SIP 0174_s:ENE20",,"N093E012_versciaco_3.jpg;N093E012_versciaco_2.jpg;N093E012_versciaco_1.jpg"
"aisevica_???",AISE_???,SI,4556.650N,01342.150E,61.0m,3,300,300.0m,,,"per ULM dir 12/30 visto su sito web aidussina - da controllare s:ENE20",,
"AJDOVSCINA_AE",LJAJ_AE,SI,4553.217N,01353.500E,116.0m,2,90,1200.0m,,"123.500","traino disponibile s:ENE20",,"IMG7901.jpg;IMGCB17.jpg;IMG553D.jpg"
"Bovec_AE",LJBO_AE,SI,4619.726N,01332.914E,434.0m,2,70,950.0m,,"123.500","chiamare torre ATTENZIONE possibili lanci para leggera salita verso NE atterrare per 70 s:ENE20",,"IMGAF43.jpg;IMGE1D8.jpg"
"Cepovan_7",CEPOV_7,SI,4602.117N,01347.000E,570.0m,3,20,300.0m,,,"ATTERRARE SOLO IN DIREZIONE 02 PENDENZA A SALIRE VERSO NORD SOTTOVENTO DX PER 20 s:ENE20",,"IMG1B21.jpg;IMG48D6.jpg;IMG7543.jpg;IMGA1FF.jpg"
"Divaca_AE",DIVAC_AE,SI,4540.998N,01400.090E,430.0m,2,120,800.0m,,"123.500","pista12/30 in erba per alianti 13/31 in asfalto s:ENE20",,"IMG57C7.jpg;IMG7D71.jpg;N091E013_divaca.jpg"
"Lesce-Bled_AE",LJBL,SI,4621.483N,01410.400E,505.0m,2,130,600.0m,,"123.500","Gliders FRQ:124.950 s:ENE20",,"IMGAF5F.jpg;IMGDB6F.jpg;IMGA7B.jpg"
"Mojstrana_6?",Mojst_6?,SI,4627.950N,01355.250E,660.0m,3,300,300.0m,,,"MEDIO atterrare solo per 30/- dopo la stradina nella ultima parte del campo - dosso al centro del campo s:ENE20",,"N092E013_mojstrana_1.jpg;N092E013_mojstrana_2.jpg;N092E013_mojstrana_3.jpg"
"Podnano_6?",Podna_6?,SI,4548.433N,01357.867E,146.0m,3,170,1000.0m,,,"dir 17/35 segnalati ostacoli - da verificare fonte: sito web aiussina s:ENE20",,
"Postoina_AE",LIPO,SI,4545.200N,01411.700E,525.0m,2,20,750.0m,,"123.500","CVA0 100 s:ENE20",,"N091E014_postumia.jpg"
"Vipava_8?",VIPAV_8?,SI,4549.883N,01356.983E,108.0m,3,180,300.0m,,,"dir 18/36 pista modellistO - fonte: sito web aidussina s:ENE20",,"N091E013_VIPAVA_1.jpg"
"BISUSCHIO_8",BISUSCH8,IT,4552.667N,00852.633E,350.0m,3,330,400.0m,,,"Bisuschio s:valb20",,"N091E008_BISUSCHIO_1.png;N091E008_BISUSCHIO_2.png"
"BORMIO_6",BORMIO6,IT,4627.483N,01022.033E,1200.0m,3,225,400.0m,,,"Bormio  s:valb20",,"N092E010_BORMIO_1.png;N092E010_BORMIO_2.png"
"BORMIONW_6",BORMIN6,IT,4628.617N,01021.650E,1235.0m,3,180,,,,"Bormio, entrare da N salita leggera s:valb20",,"N092E010_BORMIO_NW_1.png;N092E010_BORMIO_NW_2.png"
"CAIOLO_9",CAIOL9,IT,4609.250N,00947.883E,274.0m,5,80,1050.0m,,"129.500","Flugplatz s:valb20",,"N092E009_CAIOLO_1.png;N092E009_0119.jpg"
"CHIURO_8",CHIURO8,,4609.617N,01000.867E,320.0m,3,0,,,,"Having landing 270° touch down after 100m from the street. W125Scheda CVA http://www.ava-valbrembo.it",,"N092E010_CHIURO_1.png;N092E010_CHIURO_2.png;N092E010_img990.jpg"
"CLUSONE_8",CLUSO8,IT,4552.800N,00956.467E,550.0m,3,80,400.0m,,,"Clusone 80/260 Attenzione al fosso a est della fattoria s:valb20",,"N091E009_CLUSONE_1.png;N091E009_CLUSONE_2.png"
"Cortenova_4",CORTEN_4,IT,4600.267N,00922.867E,460.0m,3,140,,,,"Cortenova, FORSE meglio Taceno, solo 140 Scheda http://www.ava-valbrembo.it 2020",,"N092E009_CORTENOVA_1.png;N092E009_CORTENOVA_2.png"
"Deggiano_5",Deggian5,IT,4619.350N,01051.267E,805.0m,3,65,200.0m,,,"Deggiano pref 65 attenzione rete e paletti Pellizzano e Male sono sono meglio Scheda http://www.ava-valbrembo.it 2020",,"N092E010_DEGGIANO_1.png;N092E010_DEGGIANO_2.png"
"DUBINO_9",DUBINO9,IT,4609.083N,00926.967E,180.0m,3,150,400.0m,,,"Scheda http://www.ava-valbrembo.it 2020",,"N092E009_DUBINO_1.png;N092E009_DUBINO_2.png"
"GAVARDO_7",GAVARDO7,IT,4534.433N,01027.000E,270.0m,3,150,,,,"Entrata solo da NW in salita Alternative presenti Scheda http://www.ava-valbrembo.it 2020",,"N091E010_GAVARDO_1.png;N091E010_GAVARDO_2.png"
"Gironico_5",Giron_5,IT,4547.950N,00900.050E,360.0m,3,20,250.0m,,,"Solo da S, Linee elettricheScheda http://www.ava-valbrembo.it 2020",,"N091E008_GIRONICO_1.png;N091E008_GIRONICO_2.png"
"BRESCIA_6",BRESCIA6,IT,4534.367N,01012.767E,195.0m,3,200,,,,"Ingresso N, circuito SX? Scheda http://www.ava-valbrembo.it 2020",,"N091E010_BRESCIA_1.png;N091E010_BRESCIA_2.png"
"BRIVIO_ZA8",BRIV_ZA8,IT,4543.867N,00927.033E,190.0m,3,180,300.0m,,,"Brivio Scheda http://www.ava-valbrembo.it 2020",,"N091E009_BRIVIO_1.png;N091E009_BRIVIO_2.png"
"PIANCOGNO_8",PIANC_8,IT,4554.517N,01012.717E,221.0m,3,45,400.0m,,,"Piancogno. Ingresso per recupero alla chiesa direzione cimitero Scheda http://www.ava-valbrembo.it 2020",,"N091E010_PIANCOGNO_1.png;N091E010_PIANCOGNO_2.png"
"PoggiRidenti_8",POGGIR_8,IT,4609.900N,00956.050E,273.0m,3,90,300.0m,,,"Poggi Ridenti Scheda http://www.ava-valbrembo.it 2020",,"N092E009_POGGIRIDENTI_1.png;N092E009_POGGIRIDENTI_2.png"
"PORLEZZA_za7",PORL_ZA7,IT,4602.067N,00909.033E,275.0m,3,90,400.0m,,,"Ingresso N o W!, Scheda http://www.ava-valbrembo.it 2020",,"N092E009_PORLEZZA_1.png;N092E009_PORLEZZA_2.png"
"POSCHIAVO_za8",POSC_ZA8,CH,4617.900N,01004.717E,980.0m,3,150,500.0m,,,"Poschiavo Scheda http://www.ava-valbrembo.it 2020",,"N092E010_POSCHIAVO_1.png;N092E010_POSCHIAVO_2.png"
"PROVAGLIO_7",PROVAGL7,IT,4537.933N,01002.300E,300.0m,3,30,300.0m,,,"Provaglio, MAIS: SOLO A PRIMAVERA, Scheda http://www.ava-valbrembo.it 2020",,
"ROVETTA_7",ROVETTA7,IT,4553.233N,00958.550E,600.0m,3,180,300.0m,,,"Rovetta, ingresso solo N, Scheda http://www.ava-valbrembo.it 2020",,"N091E009_0131.jpg;N091E009_img1024.jpg"
"SANVALENTINO_7",SVALEN_7,IT,4644.717N,01032.000E,1470.0m,3,180,400.0m,,,"ATTERRAGGIO N-S Scheda http://www.ava-valbrembo.it 2020",,"N093E010_SVALENTINO_1.png;N093E010_SVALENTINO_2.png"
"SLUDERNO_?",SLUDER_?,IT,4639.700N,01034.417E,900.0m,3,130,400.0m,,,"RISCHIOSO: cambio destinazione. PALI IRRIGAZIONE A SW STARE A NE DELLA STRADA Scheda http://www.ava-valbrembo.it 2020",,"N093E010_SLUDERNO_1.png;N093E010_SLUDERNO_2.png"
"SAMOLACO_UL",SAMO_UL9,IT,4614.167N,00925.867E,210.0m,2,140,300.0m,,,"STRETTINA AKA Somaggia, corrette le coordinate Scheda http://www.ava-valbrembo.it 2020",,"N092E009_SOMAGGIA_1.png;N092E009_SOMAGGIA_2.png"
"Stadolina_5",Stadol_5,IT,4614.467N,01025.933E,1056.0m,3,270,300.0m,,,"PREFERIBILE ATTERRARE DA E Scheda http://www.ava-valbrembo.it 2020",,"N092E010_STADOLINA_1.png;N092E010_STADOLINA_2.png"
"STORO_8",STORO_8,IT,4549.883N,01033.533E,395.0m,3,40,450.0m,,,"MAIS: USABILE SOLO PRIMAVERA Scheda http://www.ava-valbrembo.it 2020",,"N091E010_STORO_1.png;N091E010_STORO_2.png"
"Taceno_UL??",Taceno_??,IT,4600.800N,00922.050E,500.0m,2,315,220.0m,,"130","SAN 2020: SEMBRA DISMESSA STRETTA! Scheda http://www.ava-valbrembo.it 2020",,"N092E009_TACENO_1.png;N092E009_TACENO_2.png"
"TONALE_UL",TONA_UL9,IT,4615.814N,01035.965E,1920.0m,2,70,1000.0m,,"121.65","070 250 Scheda http://www.ava-valbrembo.it 2020",,"N092E010_TONALE_1.png;N092E010_TONALE_2.png;N092E010_0053.jpg"
"Tonale_za4",Tona_ZA4,IT,4615.267N,01034.450E,1885.0m,3,80,200.0m,,,"Tonale ZA - PRENDERE L'ALTRA (PISTA UL) Scheda http://www.ava-valbrembo.it 2020",,
"Vezza_4",Vezza4,IT,4614.200N,01024.167E,1040.0m,3,270,300.0m,,,"Solo 270 con circuito DX Vezzano Scheda CVA http://www.ava-valbrembo.it 2020 - W126 ",,"N092E010_VEZZA_DOGLIO_1.png;N092E010_VEZZA_DOGLIO_2.png"
"PELLIZZANO_za8",PELL_za8,IT,4618.616N,01045.866E,960.0m,3,80,450.0m,,,"080 - 260 - Pellizzano -  Scheda CVA http://www.ava-valbrembo.it 2020",,"N092E010_PELLIZZANO_1.png;N092E010_PELLIZZANO_2.png"
"PELUGO_za6",PELU_za6,IT,4605.550N,01044.000E,680.0m,3,20,200.0m,,,"200/020 INGRESSO N UNO VICINO FIUME E (MENO BUONO) VICINO ALLA STRADA Scheda http://www.ava-valbrembo.it 2020",,"N092E010_PELUGO_1.png;N092E010_PELUGO_2.png;N092E010_img1027.jpg"
"GIUSTINO_6",GIUSTIN6,IT,4608.305N,01045.964E,760.0m,3,190,200.0m,,,"Giustino Scheda http://www.ava-valbrembo.it 2020",,"N092E010_GIUSTINO_1.png;N092E010_GIUSTINO_2.png"
"GORLE_7",GORLE_7,IT,4542.467N,00943.400E,270.0m,3,20,300.0m,,,"DUE campi, alternative vicine Scheda http://www.ava-valbrembo.it 2020",,"N091E009_GORLE_1.png;N091E009_GORLE_2.png"
"Iseo_4",ISEO_4,IT,4539.117N,00959.883E,199.0m,3,50,300.0m,,,"If all else fails Scheda http://www.ava-valbrembo.it 2020",,"N091E009_ISEO_1.png;N091E009_ISEO_2.png"
"KONG_UL9",KONG_UL9,IT,4545.783N,00926.733E,200.0m,2,180,300.0m,,"130","Scheda http://www.ava-valbrembo.it 2020",,"N091E009_KONG_1.png;N091E009_KONG_2.png"
"LAPONCIA_8",LAPON8,IT,4547.783N,00919.183E,225.0m,3,10,500.0m,,," 010-350. La Poncia, Scheda CVA http://www.ava-valbrembo.it 2020 W137",,"N091E009_LA_PONCIA_1.png;N091E009_LA_PONCIA_2.png"
"LIVIGb_7",LIVIb7,IT,4632.667N,01008.583E,1810.0m,3,180,300.0m,,,"Scheda CVA http://www.ava-valbrembo.it 2020",,"N093E010_LIVIGNO_1.png;N093E010_LIVIGNO_2.png"
"LIVIGa_6",LIVIa6,IT,4632.117N,01008.250E,1810.0m,3,30,300.0m,,,"A158+Außerhalb der markierten Felder sind Bewässerungsgräben und Bodenwellen! W116. Kat 1 non sul CVA",,
"LOVERE_ZA8",LOVE_za8,IT,4549.183N,01005.500E,190.0m,3,45,300.0m,,,"ZA, aviosuperficie corta vicinaScheda http://www.ava-valbrembo.it 2020",,"N091E010_LOVERE_1.png;N091E010_LOVERE_2.png"
"LOVERE_ul8",LOVERul8,IT,4548.983N,01005.767E,182.0m,2,40,480.0m,22.0m,,"Iseo Aviosuperficie corta - aggiunta da sandro, non c'era in Valbrembo",,
"MALE_7",MALE_7,IT,4620.367N,01054.267E,740.0m,3,70,400.0m,,,"Male - meglio Pellizzano, attenzione - a S della strada, non distante dallo split  70-260 A164 Scheda CVA http://www.ava-valbrembo.it 2020",,"N092E010_MALE_1.png;N092E010_MALE_2.png;N092E010_0054.jpg"
"MUSCOLINE_7",MUSCOL_7,IT,4533.250N,01026.617E,187.0m,3,190,300.0m,,,"Solo da N Scheda CVA http://www.ava-valbrembo.it 2020",,"N091E010_MUSCOLINE_1.png;N091E010_MUSCOLINE_2.png"
"PASTURO_7",PASTUR_7,IT,4556.467N,00927.217E,600.0m,3,160,250.0m,,,"NON UTILIZZABILE IN ESTATE SOLO 160 Scheda CVA http://www.ava-valbrembo.it 2020",,"N091E009_PASTURO_1.png;N091E009_PASTURO_2.png"
"CIMOLAIS_6?",CIMOL7?,IT,4616.333N,01227.850E,570.0m,3,330,200.0m,,,"Cimolais Landing direction 330°. Kat 1. W60 A43 source:SAN",,
"Laghi_za??",Lag_za??,IT,4558.367N,01211.550E,180.0m,3,0,,,,"source:SAN",,
"A260+SILLo_A_??",Silla_??,AT,4644.884N,01227.044E,1070.0m,3,40,350.0m,,,"Ostliche Wiese Zaunstempel! Kat 1 source:SAN",,
"A120+INNICHEN_A_?",INNIA_?,IT,4643.859N,01217.612E,1170.0m,3,110,300.0m,,,"Auf Zaunstempel am Rande der Wiese achten! Kat 1 source:SAN",,
"A243-SCHABS_5?",SCHAB_5?,IT,4645.274N,01138.669E,700.0m,3,40,300.0m,,,"UL-Flugplatz??, narrow and short: alternative Mais fields available till June. Anflug nur 22m breit, Piste sehr eng und kurz! Alternativen, Maisfelder nur bis Juni nutzbar! Kat 2 source:SAN",,
"ALBEINS_ZA5?",ALBza?,IT,4639.767N,01136.600E,640.0m,3,40,300.0m,,,"Landefeld source:SAN",,
"ALIGRAT_UL9",ALIG_UL9,IT,4533.521N,01158.506E,50.0m,2,190,700.0m,,,"Ali Sul Graticolato UL, aggiunto io source:SAN",,
"ALIVENETE_UL9",ALIV_UL9,IT,4539.900N,01148.420E,47.0m,2,130,400.0m,,,"Ali Venete aka Cittadella source:SAN",,
"ARCA_UL9",ARCA_UL9,IT,4544.592N,01150.141E,80.0m,2,270,500.0m,,,"090/270 Bella. Check posizione: a S della strada, a E dell'altra source:SAN",,
"ASOLO_A",ASOLO_A,IT,4545.500N,01153.767E,80.0m,2,170,360.0m,,,"UL. It source:SAN",,
"BAGNOLI_UL9",BAGN_UL9,IT,4511.040N,01151.480E,0m,2,170,630.0m,,,"source:SAN",,
"BARCOnew_7",BARCON_7,IT,4600.646N,01120.396E,430.0m,3,60,250.0m,,,"2020: leggermente a W del vecchio Barco UL che non funziona piu. Cavo elettrico a meta",,
"BASEBRAVO_UL9",BASE_UL9,IT,4523.569N,01141.556E,10.0m,2,360,400.0m,,,"Base Bravo UL, aggiunto io source:SAN",,
"BASSANO_UL9",BASS_UL9,IT,4545.300N,01141.633E,110.0m,2,10,500.0m,,,"W91 Landing direction 10°. source:SAN",,
"BOLZANO_A",BOLZA_A,IT,4627.667N,01119.583E,238.0m,5,10,1230.0m,,"120.60","W55 BOLZANOIt source:SAN",,
"BRUNI_7?",BRUN7?,IT,4648.374N,01156.528E,835.0m,3,180,400.0m,,,"A 36 Kat 2 source:SAN",,
"CAQUI_UL9",CAQU_UL9,IT,4525.991N,01123.084E,60.0m,2,70,400.0m,,,"Ca Quinta di Sarego UL source:SAN",,
"CASSOLA_UL9",CASS_UL9,IT,4544.533N,01148.383E,80.0m,2,170,460.0m,,,"Bella, a S della strada, a W dell'altra source:SAN",,
"CAVALESE_7?",CAVAL_7?,IT,4616.738N,01126.915E,832.0m,3,80,2436.0m,,,"confirmed by seeyou, but unchecked source:SAN",,
"COLLIEU_UL9",COLL_UL9,IT,4512.180N,01147.640E,7.0m,2,180,270.0m,,,"source:SAN",,
"CORRY_9",CORRY9,IT,4531.140N,01022.800E,156.0m,2,150,400.0m,,,"source:SAN",,
"CORT_AER_6",CORae6,IT,4634.533N,01206.883E,1300.0m,3,170,500.0m,,,"SOLO CON VENTO DA SUD (vedi video). Campetto a EST disponibile. Cortina Ex Aeroporto It,Mil utilizzare solo la meta' NORD della pista - sottovento sx per 16 - dx per 34. attenzione: possibile gente che passeggia in pista. source:ENE21",,
"MASCIONI_UL9",MASCIONI_UL9,IT,4553.933N,00843.367E,279.0m,5,80,300.0m,,"120.350","S:SEEYOU source:SAN",,
"DILONATO_UL9",DILO_UL9,IT,4523.640N,01033.840E,202.0m,5,50,795.0m,,,"source:SAN",,
"DOMENICO_UL9",DOME_UL9,IT,4513.980N,01147.880E,8.0m,5,32,2100.0m,,,"source:SAN",,
"FaiPagan_5?",Fai_5?,IT,4611.150N,01104.633E,927.0m,3,20,250.0m,,,"010 190 - 250m - Fai Della Paganella perhaps an old Ulm field, unchecked recently source:SAN",,
"FBARACCA_UL9",FBAR_UL9,IT,4550.500N,01211.623E,63.0m,2,150,1000.0m,,,"appena a W del fiume Enorme. Check coordinate source:SAN",,
"Feltre_5",Feltre5,IT,4601.792N,01155.205E,320.0m,3,250,300.0m,,,"Landing direction 70°. Kat 1. W76 A68+ source:SAN pictures:AVS",,"N092E011_0076.jpg;N092E011_img676.jpg;N092E011_img678.jpg"
"FERRARA_A",FERR_A,IT,4448.755N,01136.766E,6.0m,5,90,0.8m,,"122.50","source:SAN",,
"Fonzaso_5?",Fonza_5?,IT,4600.700N,01148.667E,330.0m,3,70,200.0m,,,"Sehr kurz! Horses in the garden. W74. Kat 2 source:SAN",,
"GRIGNO_7?",GRIG7?,IT,4601.753N,01134.860E,300.0m,3,310,250.0m,,,"Landing direction 310°. A198+W73. Kat 1 source:SAN pictures:AVS",,"N092E011_GRIGNO_SK.jpg;N092E011_img659.jpg"
"LAVIS_7?",LAVI7?,IT,4607.734N,01105.681E,230.0m,3,60,700.0m,,,"W69. Kat 1 A150 source:SAN pictures:AVS",,"N092E011_LAVIS_SK.jpg;N092E011_0069.jpg;N092E011_img633.jpg;N092E011_img636.jpg"
"LEPANIZZE_UL9",LEPA_UL9,IT,4525.172N,01033.447E,0m,2,130,800.0m,,,"Le Panizze UL source:SAN",,
"LERISARE_UL9",LERI_UL9,IT,4534.380N,01150.640E,10.0m,2,17,500.0m,,,"source:SAN",,
"MALONNO_6?",MALO6?,IT,4607.385N,01019.673E,600.0m,3,220,,,,"Solo 220? W128 Left downwind and Landing direction 220° source:SAN pictures:AVS",,"N092E010_MALONNO_1.png;N092E010_MALONNO_2.png"
"MOLINELLA_9",MOLIN9,IT,4436.017N,01139.467E,10.0m,4,40,1230.0m,,"126.950","Flugplatz source:SAN",,
"MONTAGN_UL9",MONTG_9,IT,4515.000N,01125.567E,20.0m,2,110,1100.0m,,"118.975","Flugplatz source:SAN",,
"OSPEDALETTO_7",OSPED7,IT,4602.500N,01132.617E,310.0m,3,120,400.0m,,,"Ospedaletto Landing direction CVE thrs 120°, A198+W72, Kat 1 source:SAN",,
"PADOLAs_6?",PADLs6?,IT,4636.317N,01228.700E,1180.0m,3,160,200.0m,,,"Landing towards 160° after the street. The field slopes up to 160°.Paths at the same field level. Secondo W24. Kat 2 A200. source:SAN",,
"Paulus_5",Paulu5,IT,4632.083N,01217.717E,1130.0m,3,100,280.0m,,,"ATTERRARE SOLO IN DIREZIONE 280 CASA E LINEE ELETTRICHE IN TESTATA 28. SENTIERI SENZA DISLIVELLI. Palus S Marco A164-Leitung im Anflug! PALUS-S-MARC  Kat 2 source:SAN pictures:AVS",,"N093E012_0043.jpg;N093E012_img470.jpg"
"PRAPAVEIza?",PRAza?,IT,4607.560N,01207.560E,335.0m,3,160,400.0m,,,"source:SAN",,
"PREDAZZO_7",PREDA7,IT,4617.533N,01135.350E,1000.0m,3,110,250.0m,,,"Downwind at S of the field. W56. Kat 1. A164 source:SAN pictures:AVS",,"N092E011_0056.jpg;N092E011_img548.jpg;N092E011_img550.jpg"
"SEDICO_ZA?",SEDza?,IT,4605.517N,01205.417E,292.0m,3,178,440.0m,,,"source:SAN",,
"SGIUST_za5",SGIU_za5,IT,4604.533N,01203.433E,290.0m,3,30,300.0m,,,"Santa Giustina W77. Kat 1 ZA A236 source:SAN",,
"SGIUST_UL8",SGIU_UL8,IT,4605.100N,01204.200E,290.0m,2,210,420.0m,,,"Campo UL 430x30 source:SAN",,
"SILVIO_UL9",SILV_UL9,IT,4531.080N,01026.940E,182.0m,5,100,2462.0m,,,"source:SAN",,
"SOLIMBER_UL7",SOLI_UL7,IT,4610.900N,01249.333E,200.0m,3,110,250.0m,,,"max 15 m wingspan. A262+W97. Kat 1 source:SAN",,
"SORLINI_UL9",SORL_UL9,IT,4530.900N,01027.900E,195.0m,5,50,795.0m,,,"source:SAN",,
"TERMON_UL6",TERM_UL6,IT,4616.246N,01101.550E,680.0m,3,240,300.0m,,,"solo 240? corto Landefeld source:SAN+webinar21, vedi di rientrare a Trento prima",,
"THIENE_A",THIEN_A,IT,4540.533N,01129.783E,104.0m,2,170,890.0m,,"121.205","LIDH 121.205 source:SAN",,
"TIGNES_UL9",TIGN_UL9,IT,4609.240N,01220.880E,509.0m,2,150,300.0m,,,"source:SAN",,
"TRENTO_A",TRENT_A,IT,4601.300N,01107.483E,189.0m,5,180,980.0m,,"119.650","Flugplatz source:SAN",,
"TRISSINO_7",TRISS7,IT,4533.683N,01123.450E,150.0m,3,180,800.0m,,,"Trissino Appena a W delle colline. A295+W96. Kat 1 source:SAN",,
"SALURN_ZA?",SALU_ZA?,IT,4613.427N,01109.273E,250.0m,3,180,500.0m,,,"A239+Kat 1  source:SAN",,
"Stara fuzina_6",STARA_6,SI,4617.367N,01354.017E,542.0m,3,90,250.0m,,,"dir 09/27 a est del lago Nuovo 2021. Sembra buono",,"N092E013_stara_1.jpg;N092E013_stara_2.jpg;N092E013_stara_3.jpg;N092E013_stara_4.jpg"
"Masera Pilone",MaseraP,IT,4608.050N,00818.372E,278.0m,1,,,,,,,
"fai 500 est",fai50est,,4635.683N,01304.333E,1706.0m,1,,,,,,,
"BELLINZPIL",BELLINZP,,4612.617N,00857.900E,1299.0m,1,,,,,"pilone task",,
"Jauffenpass Gast",JAUFFE,IT,4650.383N,01119.283E,2099.0m,6,,,,,,,
"500 fai nord",500faord,,4656.783N,01117.400E,2520.0m,1,,,,,,,
"PASSUD",PASSUD,,4534.417N,01050.633E,740.0m,1,,,,,"pilone task",,
"Pasubio est",Pasubest,,4546.767N,01113.700E,1200.0m,1,,,,,"pilone task",,
"750faiest",750faest,AT,4718.467N,01437.333E,1867.0m,1,,,,,"pilone task",,
"750faiinn",750fainn,AT,4715.917N,01135.617E,1226.0m,1,,,,,"pilone task",,
"750faimay",750famay,AT,4721.067N,01210.433E,1921.0m,1,,,,,"piloje task",,
"750maut",750maut,AT,4709.450N,01340.333E,1851.0m,1,,,,,"pilone task",,
"750maute",750maute,AT,4709.700N,01341.017E,1618.0m,1,,,,,"pilonetask",,
"BOSCOCHIESANUOVA",BOSCO,IT,4537.183N,01102.117E,1063.0m,1,,,,,"pilone task",,
"CAREGA1",CAREGA1,IT,4541.633N,01107.917E,1517.0m,1,,,,,"pilone task",,
"CAREGA2",CAREGA2,IT,4543.900N,01106.300E,1746.0m,1,,,,,"pilone task",,
"CERMISPIL",Cermipil,IT,4613.650N,01128.683E,2039.0m,1,,,,,"pilone task",,
"500ESTPIL",500ESPIL,SI,4613.317N,01356.450E,1195.0m,1,,,,,"pilone task",,
"OlgiascaPIL",OlPIL,IT,4606.963N,00918.950E,309.0m,1,,,,,"Pilone",,
"Mulhel PIL",MulPIL,IT,4649.077N,01150.899E,975.0m,1,,,,,"Pilone",,
"500FAI E",500FAIE,SI,4615.185N,01331.274E,614.0m,1,,,,,"Pilone a E",,
"Pil Erbe",PilEr,IT,4639.624N,01147.112E,1863.0m,1,,,,,"Pilone passo erbe",,
"CUW_1",CUW_1,,4620.692N,01438.243E,1954.0m,1,,,,,,,
"CUW_2",CUW_2,,4613.277N,01455.308E,522.0m,1,,,,,,,
"CUW_3",CUW_3,,4707.867N,01229.576E,1878.0m,1,,,,,,,
"CUW_4",CUW_4,,4607.930N,00818.237E,278.0m,1,,,,,,,
"CUW_5",CUW_5,,4624.647N,01501.927E,515.0m,1,,,,,,,
"CUW_6",CUW_6,,4702.835N,01231.055E,1286.0m,1,,,,,,,
"CUW_11",CUW_11,,4614.918N,01333.005E,282.0m,1,,,,,,,
"CUW_12",CUW_12,,4641.096N,01147.469E,1890.0m,1,,,,,,,
"CUW_13",CUW_13,,4658.020N,01155.865E,1092.0m,1,,,,,,,
"CUW_14",CUW_14,,4658.113N,01157.375E,1750.0m,1,,,,,,,
"CUW_15",CUW_15,,4657.050N,01411.712E,1132.0m,1,,,,,,,
"CUW_19",CUW_19,,4639.352N,01146.607E,2385.0m,1,,,,,,,
"CUW_18",CUW_18,,4615.255N,01330.725E,438.0m,1,,,,,,,
"CUW_20",CUW_20,,4615.620N,01331.522E,939.0m,1,,,,,,,
"CUW_21",CUW_21,,4656.714N,01118.150E,2255.0m,1,,,,,,,
"CUW_24",CUW_24,,4606.748N,00919.195E,394.0m,1,,,,,,,
"CUW_23",CUW_23,,4649.100N,01150.890E,974.0m,1,,,,,,,
"CUW_25",CUW_25,,4702.452N,01230.908E,1134.0m,1,,,,,,,
-----Related Tasks-----
"752.1 FAI triangle","???","PASSUD","Šoštanj_AE","CUW_25","PASSUD","???"
ObsZone=0,Style=2,R1=3000m,A1=45
ObsZone=2,Style=1,R1=1000m,A1=45
ObsZone=3,Style=3,R1=3000m,A1=45
"500 FAI ovest II","???","BOSCOCHIESANUOVA","OlgiascaPIL","Mulhel PIL","BOSCOCHIESANUOVA","???"
ObsZone=0,Style=2,R1=3000m,A1=45,Line=1
ObsZone=3,Style=3,R1=3000m,A1=45,Line=1
"TSK 564.6 Triangle","???","PASSUD","CUW_20","CUW_21","PASSUD","???"
ObsZone=0,Style=2,R1=1000m,A1=45
ObsZone=1,Style=1,R1=1000m,A1=45
ObsZone=2,Style=1,R1=1000m,A1=45
ObsZone=3,Style=3,R1=1000m,A1=45
"TSK 502.9 FAI triangle","???","PASSUD","500FAI E","Pil Erbe","PASSUD","???"
ObsZone=0,Style=2,R1=1000m,A1=45
ObsZone=1,Style=1,R1=1000m,A1=45
ObsZone=2,Style=1,R1=1000m,A1=45
ObsZone=3,Style=3,R1=1000m,A1=45
"TSK 614.6 Out and return","???","PASSUD","Eisenkappel_?","PASSUD","???"
ObsZone=0,Style=2,R1=1000m,A1=45
ObsZone=1,Style=1,R1=1000m,A1=45
ObsZone=2,Style=3,R1=1000m,A1=45
"TSK 601.3 FAI triangle","???","PASSUD","500ESTPIL","CUW_14","PASSUD","???"
ObsZone=0,Style=2,R1=1000m,A1=45
ObsZone=1,Style=1,R1=1000m,A1=45
ObsZone=2,Style=1,R1=1000m,A1=45
ObsZone=3,Style=3,R1=1000m,A1=45
"500 FAI ovest","???","PASSUD","BELLINZPIL","Jauffenpass Gast","PASSUD","???"
ObsZone=0,Style=2,R1=3000m,A1=45,Line=1
ObsZone=3,Style=3,R1=3000m,A1=45,Line=1
"750fai NE","???","BOSCOCHIESANUOVA","750faiest","750faiinn","BOSCOCHIESANUOVA","???"
ObsZone=0,Style=2,R1=3000m,A1=45
ObsZone=3,Style=3,R1=3000m,A1=45
"755.9 FAI NOvest","???","BOSCOCHIESANUOVA","750faimay","CUW_4","BOSCOCHIESANUOVA","???"
ObsZone=0,Style=2,R1=3000m,A1=45
ObsZone=2,Style=1,R1=1000m,A1=45
ObsZone=3,Style=3,R1=3000m,A1=45
"TSK 501.8 Out and return","???","PASSUD","500ESTPIL","PASSUD","???"
ObsZone=0,Style=2,R1=3000m,A1=45
ObsZone=2,Style=3,R1=3000m,A1=45
"TSK 750.8 FAI triangle","???","PASSUD","CUW_5","CUW_6","PASSUD","???"
ObsZone=0,Style=2,R1=3000m,A1=45
ObsZone=2,Style=1,R1=1000m,A1=45
ObsZone=3,Style=3,R1=3000m,A1=45
"500 FAI nord","???","PASSUD","fai 500 est","500 fai nord","PASSUD","???"
ObsZone=0,Style=2,R1=3000m,A1=45,Line=1
ObsZone=3,Style=3,R1=3000m,A1=45,Line=1